### PR TITLE
LPD-24819 Remove Feature.Flag Dropdown from Portal.Properties

### PR DESCRIPTION
**Pull request by SelenaAungst**
https://liferay.atlassian.net/browse/LPD-24819

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
Hey @SelenaAungst, we probably do not need to have an condition for `feature.flag.*` properties anymore. I think we can [remove the if on line 39](https://github.com/liferay-platform-experience/liferay-portal/pull/584/files#diff-5cb17c64a23dfa793c07414f60bb37d6017c626d32ab2d40132baf6169a63a8aR39).

Also, [we have a logic to handle values with 80+ characters](https://github.com/liferay-platform-experience/liferay-portal/pull/584/files#diff-5cb17c64a23dfa793c07414f60bb37d6017c626d32ab2d40132baf6169a63a8aR75). But the condition

```
<c:when test="<%= value.length() > 80 %>">
...
```

is unnecessary because  `StringUtil.shorten(value, 80)` already handles that. Could you simplify it, please?

**Comment by SelenaAungst** [comment]
Hi @thiago-buarqque,
I made these changes, please let me know if there is anything else I can add!

**Review by thiago-buarqque — APPROVED** [review]
That looks good :rocket:. Thanks @SelenaAungst

**Comment by SelenaAungst** [comment]
ci:forward

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
I am looking into this SF failure

**Comment by ethib137** [comment]
Hey @SelenaAungst , once you figure out the SF issue please mention me so that I can review this before it's forwarded. Thanks.

**Comment by thiago-buarqque** [comment]
hey @ethib137, I talked to Selena yesterday and she said I could send the SF fix. See #590.

She created a thread to try solve this issue on her machine. https://liferay.slack.com/archives/C1SJ64S9X/p1715188536595929

**Pull request closed without merging**
