### PR TITLE
LPD-26025 Update packages `@clayui/*` to v3.115.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/css:** LPD-26719 Cadmin checkboxes should have darker borders for accessibility ([ac48a01](https://github.com/liferay/clay/commit/ac48a01b711363986cc8ed95347bf2f9e9ce3b0e))
-   **@clayui/empty-state:** fixes bug when always trying to render the image for reduced motion when disabled ([1b117d0](https://github.com/liferay/clay/commit/1b117d03555ddfa8eb70fb7ce169d4e71a9f43d9))

### Bug Fixes

-   **@clayui/core:** Fixes bug when rendering the last columns visibility cell for dynamic rendering ([8621482](https://github.com/liferay/clay/commit/862148209afc3952c27ab8018c4e3cb598ebfe0e))
-   **@clayui/empty-state:** LPD-2278 Add flexbox property to prevent image to overlap text ([cb3285e](https://github.com/liferay/clay/commit/cb3285e22f26058114a29b3ed5a09ae3b0c1097e))

### Bug Fixes

-   **@clayui/core:** fixes bug when not rendering the action cell ([5f6eec5](https://github.com/liferay/clay/commit/5f6eec58859d9153a19a92cddcee0d8cc5a2c9fa))

### Features

-   **@clayui/button:** LPD-23703 Use btn-group-spaced to space buttons instead of btn-group-item ([bf1275e](https://github.com/liferay/clay/commit/bf1275e5d132b03e7b52970c5328e4a3ee4b3541))
-   **@clayui/core:** add new API to omit a column to columns visibility ([2e8d0f6](https://github.com/liferay/clay/commit/2e8d0f60d886251063b1833a38c4c72c8e07f051))
-   **@clayui/core:** adds new width API for the picker ([c37d3d4](https://github.com/liferay/clay/commit/c37d3d466c5b9ec35e109ffc43f14be04b7a96dc))
-   **@clayui/core:** changes the API behavior to only define the width ([17681fb](https://github.com/liferay/clay/commit/17681fb2ab356237a10cff11a0cc5ba82eb6720a))
-   **@clayui/css:** LPD-23703 Adds btn-group-spaced for a separated button group ([bfbd088](https://github.com/liferay/clay/commit/bfbd08844de6d83c8f0d5e27771d80735a9e8104))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:stop

**Comment by matuzalemsteles** [comment]
ci:stop

**Comment by matuzalemsteles** [comment]
ci:test:stable

**Comment by matuzalemsteles** [comment]
Depends on a new Clay release to include the fix [#5824](https://github.com/liferay/clay/pull/5824).

**Comment by matuzalemsteles** [comment]
ci:test:stable

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Stable tests are passing now and the fails appear unrelated. cc @ethib137

**Comment by ethib137** [comment]
ci:report:2572474077

**Comment by ethib137** [comment]
Thanks @matuzalemsteles . LGTM

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
