### PR TITLE
LPD-43786 - Enable system feature flags via Playwright

### PR DESCRIPTION
**Pull request by thiago-buarqque**
https://liferay.atlassian.net/browse/LPD-43786

# Issue

Currently we cannot enable/disable system feature flags using the Playwright feature flag fixture

I used the following regex to replace the usages of the fixture

```regex
'((.*)-\d+)':\s*(true|false)
```

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by ethib137 — APPROVED** [review]
Thanks @thiago-buarqque . This looks good to me.

**Comment by ethib137** [comment]
Feel free to forward once SF and tests are passing.

**Comment by pat270** [comment]
@thiago-buarqque I found https://github.com/liferay-platform-experience/liferay-portal/blob/0a85d4deaf163e6ad6a2c06f03e96803b7a573c7/modules/test/playwright/tests/feature-flag-web/featureFlag.spec.ts#L19-L20 Do these need to be converted to `{enabled: false}`?

**Comment by thiago-buarqque** [comment]
@pat270 oooff, it should be converted as well, thanks man. Missed that

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
@thiago-buarqque, I've fetched your branch and saw the change you made on `playwright/tests/commerce/commerce-site-initializer/guestCheckout.spec.ts` but the file is not on the commit. 
Any guess of what might be?

**Comment by thiago-buarqque** [comment]
@ilzamcmed it's probably a new file, or changes someone made. Then when we sync, we get errors. Normal when changing a lot of files

**Comment by thiago-buarqque** [comment]
@ethib137 @pat270 once you guys give me a thumbs up, I will rebase the branch, fix the conflicts and handle the new code

**Review by ilzamcmed — APPROVED** [review]
Thanks @thiago-buarqque!
`commerce-site-initializer/guestCheckout.spec.ts` is really a new file.

**Comment by thiago-buarqque** [comment]
Thanks for checking out @ilzamcmed

**Comment by pat270** [comment]
LGTM!

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:stable

**Comment by thiago-buarqque** [comment]
ci:forward:force

**Pull request closed without merging**
