### PR TITLE
LPD-39924 - Add CMS Sidebar and Sidebar Trigger fragments.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-39924

This PR adds the CMS Sidebar and Sidebar Trigger fragments to the site-initializer-cms module. These fragments allow users to create a toggleable sidebar with a cusomizable header and body. There is a separate `Sidebar Trigger` fragment to allow for the trigger to be placed dynamically on the page. The only requirement is that the `Sidebar Trigger` is placed inside of the `Sidebar` fragment. This allows them to communicate.

To test this deploy the `site-initializer-cms` module and create a new site based on the CMS site template. When you navigate to the site pages you will see the following view:

Screenshot 2024-11-28 at 10 51 02 AM

Screenshot 2024-11-28 at 10 51 18 AM

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:sf

**Comment by pat270** [comment]
@ethib137 do we need to activate a feature flag or something? I deployed `site-initializer-cms` and can't get CMS site template to show up via Application Menu > Control Panel > Sites > New.

**Comment by SelenaAungst** [comment]
Hi @ethib137 @pat270 I tried to test this as well but did not see the CMS site template either, is there something we need to import to test this, or more steps to reproduce this?

**Comment by ethib137** [comment]
@pat270 @SelenaAungst Yes a feature flag is needed for this. You can see it [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/site-initializer/site-initializer-cms/bnd.bnd#L4) LPD-17809

**Comment by SelenaAungst** [comment]
Ah thanks @ethib137

I just tested with the feature flag and I was able to reproduce everything. It looks good to me, everything matches with the screenshots in the PR description, and there are no log errors.

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Failures are unrelated. I'm going to manually forward to Brian.

**Comment by ethib137** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/156688

**Pull request closed without merging**
