### PR TITLE
LPD-6611 add UI for themeCSS frontend token definition

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-7079

Resent from: https://github.com/liferay-platform-experience/liferay-portal/pull/520

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
Unrelated CI errors, forwarding to Brian

**Comment by thiago-buarqque** [comment]
ci:forward:force

**Comment by thiago-buarqque** [comment]
ci:forward:force

**Pull request closed without merging**
