### PR TITLE
LPS-199223 Publications dropdown menu should be above the search bar

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPS-199223

I inlined the `z-index` here because we run into a chicken or the egg problem. If I set the `z-index` of all dropdown menus higher than sticky-top, dropdown menus lower on the page will overlap the sticky nav.

instance-settings
system-settings

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Review by ethib137 — APPROVED** [review]
LGTM, thanks @pat270

**Comment by ethib137** [comment]
@eltonccdantas could you check these failing tests and forward if it looks okay?

**Comment by eltonccdantas** [comment]
The failures look unrelated to this pull request.

[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1698682698722&testrayRunIdA=2446948333&testrayRunIdB=2448496016)

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
