### PR TITLE
LPS-198267 Moves some sidebar-sm styles to Clay

### PR DESCRIPTION
**Pull request by pat270**
- See https://github.com/liferay/clay/pull/5690

https://liferay.atlassian.net/browse/LPS-198267

This is a follow up to https://github.com/liferay-peds/liferay-portal/pull/316. We shouldn't merge this until https://github.com/liferay/clay/pull/5690 gets into DXP.

/cc @veroglez

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@eltonccdantas not yet I will forward it when ready. Clay release was delayed due to regressions with https://github.com/liferay/clay/pull/5696

**Comment by pat270** [comment]
@eltonccdantas just letting you know I didn't forget about this. We are waiting for https://github.com/liferay/clay/releases/tag/v3.106.0 to get in master. It looks like we're still on 3.105.0 at this time.

**Comment by eltonccdantas** [comment]
ci:forward

**Comment by eltonccdantas** [comment]
> @eltonccdantas just letting you know I didn't forget about this. We are waiting for https://github.com/liferay/clay/releases/tag/v3.106.0 to get in master. It looks like we're still on 3.105.0 at this time.

It's already merged https://github.com/brianchandotcom/liferay-portal/pull/143353 🎉

**Pull request closed without merging**
