### PR TITLE
LPD-35068

### PR DESCRIPTION
**Pull request by SelenaAungst**
https://liferay.atlassian.net/browse/LPD-35068
Modified based on https://github.com/liferay-platform-experience/liferay-portal/pull/712

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
I updated this with only themeId and no themeName, I just need to add the feature flag now.

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Thanks @SelenaAungst have you tested the upgrade locally yet. I just tried it and ran into an error when creating a new style book:

```
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'themeId' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121) ~[mysql.jar:8.3.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912) ~[mysql.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1054) ~[mysql.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1003) ~[mysql.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1312) ~[mysql.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchWithMultiValuesClause(ClientPreparedStatement.java:677) ~[mysql.jar:8.3.0]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:407) ~[mysql.jar:8.3.0]
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:802) ~[mysql.jar:8.3.0]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127) ~[hikaricp.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[hikaricp.jar:?]
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:125) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:110) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:153) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.getBatch(JdbcCoordinatorImpl.java:187) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3355) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3908) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478) ~[hibernate-core.jar:5.6.7.Final]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_412]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1394) ~[hibernate-core.jar:5.6.7.Final]
	at com.liferay.portal.spring.hibernate.PortletTransactionManager$TransactionStatusWrapper.reset(PortletTransactionManager.java:295) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.hibernate.PortletTransactionManager.commit(PortletTransactionManager.java:73) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.commit(DefaultTransactionExecutor.java:33) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:68) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:51) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:55) ~[portal-kernel.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy923.addStyleBookEntry(Unknown Source) ~[?:?]
	at com.liferay.style.book.web.internal.portlet.action.AddStyleBookEntryMVCActionCommand._addStyleBookEntry(AddStyleBookEntryMVCActionCommand.java:82) ~[bundleFile:?]
	at com.liferay.style.book.web.internal.portlet.action.AddStyleBookEntryMVCActionCommand.doProcessAction(AddStyleBookEntryMVCActionCommand.java:50) ~[bundleFile:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:48) ~[portal-kernel.jar:?]
```

On master I created a style book, then I ran ant all with your changes, and tried creating a new style book. It's been a while since I've worked with upgrades so let me know if I'm making any wrong assumptions about how this should work.

cc: @thiago-buarqque and @algobob

**Comment by thiago-buarqque** [comment]
@SelenaAungst @ethib137 that is because the table `StyleBookEntryVersion` also requires the new field `themeId`. I am checking the full reason for that now

**Comment by SelenaAungst** [comment]
@thiago-buarqque I see that [StyleBookEntryTable](https://github.com/liferay-platform-experience/liferay-portal/blob/0e991f104bd28407c6d53a5e74f948bcc8ea9058/modules/apps/style-book/style-book-api/src/main/java/com/liferay/style/book/model/StyleBookEntryTable.java#L76) and [StyleBookEntryVersionTable](https://github.com/liferay-platform-experience/liferay-portal/blob/0e991f104bd28407c6d53a5e74f948bcc8ea9058/modules/apps/style-book/style-book-api/src/main/java/com/liferay/style/book/model/StyleBookEntryVersionTable.java#L85) already contain themeId, does it need to be added anywhere else for this?

**Comment by thiago-buarqque** [comment]
@SelenaAungst You forgot to add the upgrade process in `StyleBookServiceUpgradeStepRegistrator.java`.

```
registry.register(
	"1.6.0", "1.7.0",
	UpgradeProcessFactory.addColumns(
		"StyleBookEntryVersion", "themeId VARCHAR(255) null"));
```

**Comment by thiago-buarqque** [comment]
That works, but tbh Idk the purpose of the table. Until now I understand that it's used to keep track of the changes of an entity. I'm just not sure we are using that for any purpose

**Comment by thiago-buarqque** [comment]
I am discussing the topic in the backend slack channel. But adding that part of the upgrade is necessary

**Comment by SelenaAungst** [comment]
Ah thanks @thiago-buarqque, I only added StyleBookEntry before and not StyleBookEntryVersion. I pushed the changes

**Comment by thiago-buarqque** [comment]
A way to test this is to ant all on master, start portal and stop it when everything finishes. Deploy the layout and style-book modules, and start portal again.

You should see
```
2024-09-24 19:14:19.389 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.style.book.internal.upgrade.registry.StyleBookServiceUpgradeStepRegistrator - Modifying table StyleBookEntry to add the columns [themeId VARCHAR(255) null]
2024-09-24 19:14:19.420 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.style.book.internal.upgrade.registry.StyleBookServiceUpgradeStepRegistrator - Modifying table StyleBookEntry to add the columns [themeId VARCHAR(255) null] in 37 ms
2024-09-24 19:14:19.429 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.style.book.internal.upgrade.registry.StyleBookServiceUpgradeStepRegistrator - Modifying table StyleBookEntryVersion to add the columns [themeId VARCHAR(255) null]
2024-09-24 19:14:19.454 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.style.book.internal.upgrade.registry.StyleBookServiceUpgradeStepRegistrator - Modifying table StyleBookEntryVersion to add the columns [themeId VARCHAR(255) null] in 25 ms
```

**Important:** upgrade.database.auto.run=true should be set in your `portal-ext.properties` file

**Comment by SelenaAungst** [comment]
@ethib137 @thiago-buarqque I added the changes. What content needs to behind a feature flag for this?

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by algobob** [comment]
> @ethib137 @thiago-buarqque I added the changes. What content needs to behind a feature flag for this?

Do we need to add feature flag here on backend :thinking: ? It seems all these changes will generate a new version on bnd, so it wouldn't affect current clients, right?

**Comment by ethib137** [comment]
Well these changes will affect current clients once they upgrade, but I don't think we need a feature flag for it since it won't break anything right now. Does that sound right, @thiago-buarqque .

**Comment by SelenaAungst** [comment]
It looks to me like everything is working for this now then! Please let me know if there is anything I missed.

**Comment by thiago-buarqque** [comment]
> Well these changes will affect current clients once they upgrade, but I don't think we need a feature flag for it since it won't break anything right now. Does that sound right, @thiago-buarqque .

@ethib137 Agreed.

**Comment by thiago-buarqque** [comment]
@SelenaAungst The CI is failing because we didn't specify the `themeId` column size in the `portlet-model-hints.xml` file. That was my bad, I missed that. 

Regarding the issue that causes:

As you can see in the commit you added the upgrade, you are specifying the `themeId` VARCHAR size to 255. That's fine. But for new databases, it would be created with size 75, which is the default. You can check [this commit](https://github.com/liferay-platform-experience/liferay-portal/pull/734/commits/a01c4e585ef640bc0348fa6603e21de5165a1d28) to see the difference.

In the image below, on the left, you can see a database that was upgraded from a previous version. And, on the right, you'll see a brand new liferay instance. As you can see, the `themeId` size differs. 
image


Sorry about that, I should've caught it before. I resent it to https://github.com/liferay-platform-experience/liferay-portal/pull/734

**Comment by SelenaAungst** [comment]
Thanks @thiago-buarqque!

**Pull request closed without merging**
