### PR TITLE
LPD-4680 - Remove h4 elements for accessibility

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-4680

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:roles

**Comment by ethib137** [comment]
ci:test:headless

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:commerce-functional

**Comment by ethib137** [comment]
ci:test:roles

**Comment by ethib137** [comment]
ci:help

**Comment by ethib137** [comment]
ci:test:headless

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:headless

**Comment by ethib137** [comment]
ci:report:2570026007

**Comment by pat270** [comment]
Closing this in favor of #604

**Pull request closed without merging**
