### PR TITLE
LPD-15984 Product Navigation Theme Contributors use liferay-npm-scrip…

### PR DESCRIPTION
**Pull request by pat270**
…ts to compile Sass

https://liferay.atlassian.net/browse/LPD-15984

product-menu
control-menu

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1317401_10301

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1357401_5280

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
