### PR TITLE
LPD-35069 - Refactor - Move out bundle tracker code

### PR DESCRIPTION
**Pull request by algobob**
Refactor:

- Move out the code responsible to extract a frontend token definition from a theme, for better readability and decoupling. It would also improve testability, enabling us to add unit tests for isolation

### CODE REVIEW

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:sf

**Comment by ethib137** [comment]
Should this PR be closed?

**Comment by algobob** [comment]
sure, I'll close it. I'll keep the branch to work more on it in a later moment. Thanks!

**Pull request closed without merging**
