### PR TITLE
LPD-40974 follow up

### PR DESCRIPTION
**Pull request by thiago-buarqque**
https://liferay.atlassian.net/browse/LPD-40974

--

There was a bug in the fix I sent here https://github.com/liferay-platform-experience/liferay-portal/pull/781

I was using the outdated preferences to update the database. Look the first commit message for more info.

### CODE REVIEW

**Review by ethib137 — APPROVED** [review]
Thanks @thiago-buarqque ... LGTM

**Review by algobob — APPROVED** [review]
LGTM :rocket:

**Comment by algobob** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:platform-experience

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
Resent to https://github.com/liferay-bpm/liferay-portal/pull/3922

**Pull request closed without merging**
