### PR TITLE
LPD-26624

### PR DESCRIPTION
**Pull request by SelenaAungst**
Ticket: https://liferay.atlassian.net/browse/LPD-26624
## Motivation
When the user tries to navigate through the following component (see the screenshot) using the Tab key, the focus is inverted:
Title input field
Language selector

Expected behaviour:
The focus should be in the following order:
Language selector
Title input field

## Proposed Solution
No new changes were added here, I just moved 1 div element further down. This switched element order allows for the focus to go to the language selector first. 

## Steps to Verify

1. Navigate to Content & Data > Web Content
2. Go to the Structures tab and create a new Structure
3. Click the Control Menu at the top of the page, then use the tab key to navigate to the Language Selector and Title input field
4. Observe focus order

## Screenshots/videos
Before:
https://github.com/liferay-platform-experience/liferay-portal/assets/101599314/875116ea-113d-43e5-84f4-dee683a8468f

After:
https://github.com/liferay-platform-experience/liferay-portal/assets/101599314/5b6a2904-4593-4563-8da2-6c986ebe298f

## Alternative Solutions that were discarded
Another solution would be to edit the focus order manually but I was not sure if this is possible/a better solution.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
Currently looking into this failure

**Comment by pat270** [comment]
@SelenaAungst since we placed the markup in the correct order, we no longer need some of the `.input-localized` styles like `order`, `row-reverse`, etc. See the files below:
```
modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/css/main.scss
modules/apps/journal/journal-web/src/main/resources/META-INF/resources/css/main.scss
modules/apps/template/template-web/src/main/resources/META-INF/resources/css/main.scss
```

**Comment by ethib137** [comment]
Hey @SelenaAungst since this is used in many different locations, we need to make sure we have checked it doesn't break something unexpected. Please test as many of it's usages as you can and take screenshots of them and add them to the description of the PR.

**Comment by SelenaAungst** [comment]
Thank you @pat270 @ethib137! I am currently working on those changes and making sure this switch didn't break anything for other locations.

**Comment by ethib137** [comment]
Thanks @SelenaAungst ... Also remember we don't own this component, so once we have completed our team review it will need to be sent to @liferay-frontend.

**Comment by SelenaAungst** [comment]
Thank you @ethib137! I resent a new PR with these changes here https://github.com/liferay-platform-experience/liferay-portal/pull/637 as I also needed to rebase. Please let me know on that PR if the changes suggested by you and @pat270 look good then I will fwd to @liferay-frontend.

**Pull request closed without merging**
