### PR TITLE
LPD-37516 Prevent more than one ThemeCSSCET from being applied at the instance level at the same time

### PR DESCRIPTION
**Pull request by ethib137**
Resent from: https://github.com/liferay-platform-experience/liferay-portal/pull/770

Original Message:

https://liferay.atlassian.net/browse/LPD-37516

# Goal

Inject the ThemeCSS CX urls into the `ThemeDisplay` (ClientExtensionsServicePreAction.java) and prevent more than one CX from being applied.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
@ethib137 I though this approach before. My concern regards the scenario where the layout is control panel and is not preview mode. 

Are we 100% sure we won't have any issues passing the control panel layout to:

```java
ThemeDisplay themeDisplay =
  (ThemeDisplay)httpServletRequest.getAttribute(
    WebKeys.THEME_DISPLAY);

themeDisplay.setFaviconURL(_getFaviconURL(layout));

_setThemeDisplayCSSURLs(
  httpServletRequest, _getThemeCSSCET(layout), themeDisplay);

ThemeSpritemapCET themeSpritemapCET = _getThemeSpritemapCET(layout);

if (themeSpritemapCET != null) {
  themeDisplay.setPathThemeSpritemap(themeSpritemapCET.getURL());
}
```

**Comment by thiago-buarqque** [comment]
Oh damn it, I just realized, the scenario I mentioned above also happens currently. Sorry 🤦

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Pull request closed without merging**
