### PR TITLE
LPD-33175

### PR DESCRIPTION
**Pull request by SelenaAungst**
Ticket: https://liferay.atlassian.net/browse/LPD-33175
## Motivation
There is no “X” button on Product menu when it shows Control Panel selection.

## Proposed Solution
Removed d-md-none from the "X" button so it is no longer hidden. 

## Steps to Verify
1. Start a clean bundle
2. Go to Control Panel > Instance Setting > Navigation
3. Uncheck “Enable Applications Menu” and Update
4. Go to HOME and open Product menu
5. Observe "X" button is missing

## Screenshots/videos (if applies)
Before:
image

With fix applied: 
image

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Review by pat270 — APPROVED** [review]
LGTM!

**Comment by pat270** [comment]
ci:forward

**Pull request closed without merging**
