### PR TITLE
LPD-4680 Convert h4 elements to use div.h4

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPD-4680

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
These failures are unrelated.

**Comment by ethib137** [comment]
Thanks @pat270 ! LGTM

**Comment by ethib137** [comment]
ci:forward:force

**Comment by ethib137** [comment]
Hey @pat270 actually one thing... We shouldn't be making any changes to the workspaces. We should leave it as is since that's not in Portal.

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Failures are unrelated. LGTM.

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
