### PR TITLE
LPD-32127 add exception mapper for PLOEntry

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Split from #678 because I want to make small improvements I found (because why not).

### CODE REVIEW

**Review by ethib137 — APPROVED** [review]
LGTM... Just one question: what happened to the invalid properties exception?

**Comment by thiago-buarqque** [comment]
@ethib137 it changed to `EmptyPropertiesFile`, the file isn't invalid, it just don't have any property in it. If the person don't send a file with `.properties` extension, then it is a invalid file. You can see this check [here](https://github.com/liferay-platform-experience/liferay-portal/blob/7eb9bfb5227259ff32700b6ed3f3c7bcec5177d1/modules/apps/portal-language/portal-language-override-web/src/main/java/com/liferay/portal/language/override/web/internal/portlet/action/ImportTranslationsMVCActionCommand.java#L81) and [here](https://github.com/liferay-platform-experience/liferay-portal/blob/7eb9bfb5227259ff32700b6ed3f3c7bcec5177d1/modules/apps/portal-language/portal-language-rest-impl/src/main/java/com/liferay/portal/language/rest/internal/resource/v1_0/MessageResourceImpl.java#L114)

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:forward

**Pull request closed without merging**
