### PR TITLE
LPD-38606 themeId must be passed to the jsonws request

### PR DESCRIPTION
**Pull request by thiago-buarqque**
For some reason CI didn't run all the functional tests related to style books. A new property was added to `StyleBookEntry` in https://github.com/liferay-platform-experience/liferay-portal/pull/734.

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:platform-experience

**Comment by ethib137** [comment]
Thanks @thiago-buarqque LGTM ... Do we need to change something about our test config to make sure all the tests do run in the future?

**Comment by ethib137** [comment]
ci:forward

**Comment by thiago-buarqque** [comment]
@ethib137 I am not sure. I found it weird, since we changed the style-book module it should've ran. I will check that and, if necessary, I will send a follow up PR

**Comment by thiago-buarqque** [comment]
It seems the problem was caused because our functional style-book tests are inside the portal-web folder. Since we haven't changed that module those tests didn't run. 

I opened [this thread](https://liferay.slack.com/archives/C19PWQ74J/p1728419291137749) to make sure of the issue. But it seems that we have to remember to run `ci:test:platform-experience` too

**Comment by thiago-buarqque** [comment]
@ethib137 
It seems the problem was caused because our functional style-book tests are inside the portal-web folder. Since we haven't changed that module those tests didn't run. 

I opened [this thread](https://liferay.slack.com/archives/C19PWQ74J/p1728419291137749) to make sure of the issue. But it seems that we have to remember to run `ci:test:platform-experience` too

**Comment by ethib137** [comment]
Thanks @thiago-buarqque that's good to know. We will have to always run that command in the future.

**Pull request closed without merging**
