### PR TITLE
LPD-30371 consistency for string attributes

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Just standardizing string attributes in our CXs samples by removing the double quotes, they aren't necessary.

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Looks great! Does everything still work as expected?

**Comment by thiago-buarqque** [comment]
Yep, just tested it

**Comment by thiago-buarqque** [comment]
Unrelated CI errors, forwarding to Brian

**Comment by thiago-buarqque** [comment]
ci:forward:force

**Pull request closed without merging**
