### PR TITLE
LPD-35070

### PR DESCRIPTION
**Pull request by ethib137**
SF for https://github.com/liferay-platform-experience/liferay-portal/pull/867

---

## Goal
To provide the theme selection when creating a style book

## Approach
Retrieve the list of available frontend token definitions and their theme ids.

## Limitation
This task does not aim to show the frontend tokens available for the chosen theme. That feature will be implemented at https://liferay.atlassian.net/browse/LPD-35071

Resent from https://github.com/liferay-platform-experience/liferay-portal/pull/791

### CODE REVIEW

**Comment by ethib137** [comment]
@SelenaAungst @thiago-buarqque , please review my changes. If everything looks okay, please feel free to send it on to BPM for the backend to be reviewed. Please specify that only the backend requires their review. 

Nice work everyone.

**Comment by ethib137** [comment]
ci:test:sf

**Review by thiago-buarqque — APPROVED** [review]

**Comment by SelenaAungst** [comment]
Thanks @ethib137 @thiago-buarqque! I will reorganize this again and send to BPM for backend review.

**Comment by SelenaAungst** [comment]
Resent here: https://github.com/liferay-bpm/liferay-portal/pull/3983

**Comment by ethib137** [comment]
Resent here: https://github.com/liferay-bpm/liferay-portal/pull/3984

**Comment by SelenaAungst** [comment]
Thanks @ethib137 !

**Pull request closed without merging**
