### PR TITLE
LPD-4680 - Remove h4 elements for accessibility

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPD-4680

This pr reverts the reverts and fixes `upload.js` selectors. I also added the `h4` class back to `card-header` since it didn't modify `font-size`, `font-weight`, `line-height`, etc.

**LocalFile.RolesandpermissionsUsecase#ExportRoleWithSiteAssignee** should pass now.

**LocalFile.SFCommerceProductDiagrams#VerifyAllPinTypeAndMappedProductInformation** fails on a different line:

`[exec]     com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[@class='data-set-wrapper' or @class='searchcontainer-content']//a[text()='Diagram1']"`

I think it's trying to add `Diagram1` and searching for it to make sure it was added. The returning json contains:

```
[exec]       "status" : "BAD_REQUEST",
[exec]       "type" : "CPDefinitionProductTypeNameException"
```

I can't reproduce the other commerce test failures. When I run them locally, they fail with the error:

```[exec]     com.jayway.jsonpath.PathNotFoundException: No results for path: $['userId']```

The server outputs:

`2024-05-16 20:42:53.685 ERROR [http-nio-8080-exec-4][JSONWebServiceServiceAction:123] Conversion failed: 34340,34902; <--- java.lang.NumberFormatException: For input string: "34340,34902"`

I also ran the tests on bchans version of master that contain your reverts. They all fail the same way.

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:roles

**Comment by pat270** [comment]
ci:test:headless

**Comment by pat270** [comment]
ci:test:commerce-functional

**Comment by pat270** [comment]
ci:test:commerce-functional

**Comment by pat270** [comment]
ci:test:headless

**Comment by pat270** [comment]
ci:test:roles

**Comment by ethib137** [comment]
ci:report:2570334136

**Comment by ethib137** [comment]
ci:test:commerce-functional

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:commerce-functional

**Comment by pat270** [comment]
ci:test:commerce-functional

**Comment by pat270** [comment]
ci:test:commerce-functional

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:commerce-functional

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:commerce-functional

**Comment by ethib137** [comment]
ci:test:commerce-functional

**Comment by ethib137** [comment]
ci:report:2571416556

**Comment by pat270** [comment]
ci:test:roles

**Comment by pat270** [comment]
ci:test:commerce-functional

**Comment by pat270** [comment]
ci:test:headless

**Comment by pat270** [comment]
ci:test:commerce

**Comment by pat270** [comment]
ci:test:commerce-upgrade

**Comment by ethib137** [comment]
ci:report:2572985107

**Comment by ethib137** [comment]
@pat270 can you review the unique failures from the csv below locally?

Testray CSV Link: [testray-results-2572985107.csv](https://test-1-8.liferay.com/userContent/jobs/generate-testray-csv/builds/68/testray-results-2572985107.csv)

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@ethib137 I wasn't able to run every test locally, but there seems to be a common failure for most of the tests.

`Caused by: com.jayway.jsonpath.PathNotFoundException: No results for path: $['userId']`

The tests I ran that are failing because of that are:
- test[LocalFile.CPCommerceProductSkusVirtualSettingsOverride#CanViewSingleSkuVirtualProductDetailPageWithSKUOverrideEnabled]
- test[LocalFile.CommerceProductDetails#CanViewSingleSkuGroupedProductDetailPage]
- test[LocalFile.CommerceProductDetails#CanViewSingleSkuVirtualProductDetailPage]
- test[LocalFile.CommerceOrderUploadCSV#CanDownloadCSVTemplate]
- test[LocalFile.CommerceMiniCartEditUnitsOfMeasure#CanEditUOMInMiniCart]
- test[LocalFile.CommerceMiniCartEditUnitsOfMeasure#CanAssertPricingTypesAreAppliedWhileEditingUOMInMiniCart]
- test[LocalFile.CommerceMiniCart#ViewMiniCartBundledProductDetails]
- test[LocalFile.CommerceProductDetails#CanViweOnlyCorrectAllowedQuantitiesAreSelectableInProductDetails]
- test[LocalFile.CommerceProductDetails#CanAssertMultipleSkusProductInvalidAllowedOrderQuantity]
- test[LocalFile.SFCommerceProductDiagrams#VerifyIfDiagramWithProductPublisherWidgets]
- test[LocalFile.SFCommerceProductDiagrams#VerifyNameAndDescriptionDefaultRender]
- test[LocalFile.SFCommerceProductDiagrams#AssertSVGTypeDiagramStoreFront]
- test[LocalFile.SFCommerceProductDiagrams#CanAddReplacementProductToCart]
- test[LocalFile.SFCommerceProductDiagrams#VerifyTooltipPinInformation]
- test[LocalFile.SFCommerceProductDiagrams#AssertDefaultTypeDiagramStoreFront]
- test[LocalFile.CommerceProductBundleRules#CanVerifyProductsLimitRuleWithDecimalUOMQuantity]
- test[LocalFile.CommerceProductBundleRules#CanVerifyIncludedAndExcludedCombiningProductsLimitRule]
- test[LocalFile.CommerceProductBundleRules#CanVerifyIncludedAndExcludedOptionValuesAreDisabledWithReasonMessageWithoutSKUContributor]

There are also tests failing because of

`java.lang.Exception: Element is present at "//*[not(self::div)][contains(@class,'btn')][normalize-space()='Sign In'][not(contains(@class,'navbar'))]"`

- test[LocalFile.CommerceSalesAgent#CannotSalesAgentWithoutPermissionsViewAndManageChannelDefaults]
- test[LocalFile.CommerceSearch#GlobalSearchSuggestedOrdersEntries]
- test[LocalFile.CommerceSalesAgent#CannotSalesAgentWithoutPermissionsViewAndManageChannelDefaults]
- test[LocalFile.CommerceSearch#GlobalSearchSuggestedOrdersEntries]

Tests that are failing because of:

`Caused by: com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//tr/td[contains(.,'Guest')]//..//button[contains(.,'Choose')]"`

- test[LocalFile.CPCommerceProductMedia#CanAddAndRemoveTagsForAttachments]
- test[LocalFile.CPCommerceProductSubscriptions#CanViewPaymentSubscriptionOnProductDetailsPageWithMultipleSKU]
- test[LocalFile.CPCommerceProducts#ProductPublishing]

There are some others, but these are the most common ones that popped up. I want to say these aren't related to the h4 change.

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
