### PR TITLE
LPD-7081 fix functional test due to button title change

### PR DESCRIPTION
**Pull request by thiago-buarqque**
@ethib137  Someone changed the label for the "search" button on the style books page. Fixed it since I was the one that created the test.

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Review by ethib137 — APPROVED** [review]
LGTM

**Comment by thiago-buarqque** [comment]
Unrelated errors on CI, forwarding to Brian

**Comment by thiago-buarqque** [comment]
ci:forward

**Pull request closed without merging**
