### PR TITLE
LPD-17968 Update packages `@clayui/*` to v3.111.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/core:** fixes bug when clicking on item does not select ([eadd182](https://github.com/liferay/clay/commit/eadd18246c2e32fb8d8dbb32a299e6d6a8727a15))
-   **@clayui/core:** fixes bug when not focusing on the first item ([f82643f](https://github.com/liferay/clay/commit/f82643f9bc651db841fc65cce22ee47e6af0c183))
-   **@clayui/core:** fixes bug when visual focus is lost when items are updated in Picker ([202962b](https://github.com/liferay/clay/commit/202962bd0c51e854994016021715e83751f4c549))
-   **@clayui/core:** fixes navigation to just Switch component instead of item ([14ad2a6](https://github.com/liferay/clay/commit/14ad2a6b85cb46c5653d065d3c77553fb599cb12))
-   **@clayui/core:** LPS-203851 fixes bug when keeping DropDown open in TreeView actions in Firefox ([f1a7dc6](https://github.com/liferay/clay/commit/f1a7dc650b2d10b8e64d93455feee2ba8205fd84))
-   **@clayui/css:** LPD-15629 Accessibility link and text should have 3:1 color contrast ([64584a6](https://github.com/liferay/clay/commit/64584a67cd73220c7011ccef1159784c6b60af57))
-   **@clayui/css:** LPD-15988 Active nav tab bottom border shouldn't depend on $body-bg ([b89b64a](https://github.com/liferay/clay/commit/b89b64a483b35d571484c722afd2f803898a23b4))
-   **@clayui/css:** LPD-16364 [@page](https://github.com/page) {.css-selector{}} is not valid css ([2df56c6](https://github.com/liferay/clay/commit/2df56c6cfaf048943d41f975329557d551f5c692))

### Features

-   **@clayui/css:** Add new icon-rule-builder icon ([33db79b](https://github.com/liferay/clay/commit/33db79b42bf25999503be4b6a8fa23111dd7f68d))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:clay

**Comment by ethib137** [comment]
Hey @matuzalemsteles thanks for this. The failures appear unrelated: https://test-1-1.liferay.com/job/generate-testray-csv/8009/

**Comment by ethib137** [comment]
@matuzalemsteles which reports with 404's are you referring to?

**Comment by matuzalemsteles** [comment]
@ethib137 Basically these tests when I click on the Poshi Report or Summary

[LocalFile.LocalizationWithSites#ConfigureSiteDefaultLanguage](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/562687//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_LocalizationWithSites_ConfigureSiteDefaultLanguage_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/LocalFile.LocalizationWithSites_ConfigureSiteDefaultLanguage/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/LocalFile.LocalizationWithSites_ConfigureSiteDefaultLanguage/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/LocalFile.LocalizationWithSites_ConfigureSiteDefaultLanguage/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/jenkins-console.txt.gz) - [Failed 1 of last 25](https://testray.liferay.com/home/-/testray/case_results/2539560413/history)
[LocalFile.WebContentExportImport#ImportAndUseGlobalStructureAndTemplate](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/562687//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_WebContentExportImport_ImportAndUseGlobalStructureAndTemplate_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/LocalFile.WebContentExportImport_ImportAndUseGlobalStructureAndTemplate/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/LocalFile.WebContentExportImport_ImportAndUseGlobalStructureAndTemplate/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/LocalFile.WebContentExportImport_ImportAndUseGlobalStructureAndTemplate/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/jenkins-console.txt.gz) - [Failed 0 of last 25](https://testray.liferay.com/home/-/testray/case_results/2539560544/history)
[LocalFile.BannerSlider#DecreaseNumberOfSlides](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/562687//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_BannerSlider_DecreaseNumberOfSlides_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/LocalFile.BannerSlider_DecreaseNumberOfSlides/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/LocalFile.BannerSlider_DecreaseNumberOfSlides/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/LocalFile.BannerSlider_DecreaseNumberOfSlides/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2024-02/test-1-32/test-portal-acceptance-pullrequest(master)/3680/functional-tomcat90-mysql57-chrome100-jdk8/8/18/jenkins-console.txt.gz) - [Failed 0 of last 25](https://testray.liferay.com/home/-/testray/case_results/2539560638/history)

**Comment by ethib137** [comment]
I'm not sure about all those cases, but for [LocalFile.LocalizationWithSites#ConfigureSiteDefaultLanguage](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/562687//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_LocalizationWithSites_ConfigureSiteDefaultLanguage_) it [failed before running the test](https://testray.liferay.com/home/-/testray/case_results/2539884839?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2539882049%26testrayRunId%3D2539882155%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse) so it makes sense that it wouldn't have generated the report or summary for it.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:clay

**Comment by matuzalemsteles** [comment]
Coming back to this again, some tests are failing on master, submit a PR to revert the changes and investigate the problem https://github.com/brianchandotcom/liferay-portal/pull/147495, I still believe it is not related because the unit test failure does not seem related to our change and the other test that is failing is related to an integration test, I will investigate this further now.

More details https://liferay.slack.com/archives/CLCD3DQLF/p1708688828371819

**Pull request closed without merging**
