### PR TITLE
LPD-7012 - Add functional tests for JS Client Extension

### PR DESCRIPTION
**Pull request by thiago-buarqque**
https://liferay.atlassian.net/browse/LPD-7012

**Resent from #539**

---

The iframe that renders the list of GlobalJS client extensions has a delay between rendering the checkbox and adding the click event on them. **I noticed that the label "select items" renders together (or after) the events are added to the checkbox.**

This is an easy solution for an issue that would require changing the select item components that uses searchcontainer to render the items. Also, would affect all portal.

I suggest to go with this and then check for a more portal-wide solution which is the one @ethib137 proposed [here](https://github.com/liferay-platform-experience/liferay-portal/pull/539#issuecomment-2032664104)

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Review by ilzamcmed — APPROVED** [review]
LGTM! :rocket: 
Thansk for this one and nice catch!

**Comment by thiago-buarqque** [comment]
ci:reevaluate:1347401_6050

**Comment by thiago-buarqque** [comment]
The errors in CI are unrelated, please @ethib137, run it again when you get back tomorrow.

**Comment by ethib137** [comment]
Forwarded with minor changes to: https://github.com/brianchandotcom/liferay-portal/pull/148764

Thanks @thiago-buarqque and @ilzamcmed, I think this is a good approach for now.

**Pull request closed without merging**
