### PR TITLE
LPD-7010 (follow up) Read and validate script element attributes from UI client extension

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Adding the validation for scriptElementAttributesJSON field coming from the Frontend. 

- I updated the way FE receives the attributes, it was expecting an array, but the data is stored as JSON string and it doesn't make sense for the BE to translate it to an array and send to the FE.
- I also found two issues on the FE:
    - It was sending an empty object `{}` when the attributes were empty, it should send an empty string
    - An boolean with false value was being translated to String due to [this](https://github.com/liferay-platform-experience/liferay-portal/pull/529/files#diff-c025c4b1e4ac02274998fbdd17f17a7a03acdb88ea20098f96dc71808d8e495cR137)

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by ilzamcmed — APPROVED** [review]
LGTM!
Thanks @thiago-buarqque  and @ethib137

**Comment by ethib137** [comment]
Resent here: https://github.com/liferay-platform-experience/liferay-portal/pull/531

@thiago-buarqque & @ilzamcmed please review my changes. 😄

**Pull request closed without merging**
