### PR TITLE
LPD-22961 update liferay-sample-global-js CX in liferay-sample-workspace with scriptElementAttributes

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Ticket: https://liferay.atlassian.net/browse/LPD-22961

Motivation
==========
Update the sample to showcase the script element attributes based on [LPD-6733 Allow developers to specify optional additional attributes to the <script> tag when deploying JS CXs from Workspace or via the Client Extensions admin](https://liferay.atlassian.net/browse/LPD-6733)
 
Preview
========
Based on the client-extension.yaml
```YAML
assemble:
    - from: build/static
      into: static
liferay-sample-global-js:
    name: Liferay Sample Global JS
    scriptElementAttributes:
        async: true
        data-attribute: "value"
        data-senna-track: "permanent"
        fetchpriority: "low"
    type: globalJS
    url: global.*.js
```

The sample now includes the following script

```HTML
<script async  type="text/javascript" data-senna-track="permanent" data-attribute="value" fetchpriority="low" src="/o/liferay-sample-global-js-2/global.a0ff2e4a08889609cd1e.js"></script>
```

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Hey @thiago-buarqque , I think this would be better to create a second global js sample for this. The reason is we want people to know that these attributes are optional. They will often create their own based on the sample and if this is the only sample they would likely leave some of these properties accidentally or because they think they are needed. So let's create a new sample that includes the attributes. You will need to also update the Readme in the workspace with the new sample. The readme also describes how to name the sample.

For the attributes in the new sample, let's not include async and defer because in this case `defer: false` would have no effect since async is already set to true. 

```
    scriptElementAttributes:
        async: true
        data-attribute: "value"
        data-senna-track: "permanent"
        defer: false
        fetchpriority: "low"
```

Does that all sound okay?

**Comment by thiago-buarqque** [comment]
@ethib137  It does, I'll do the changes, thanks for reviewing it

**Comment by thiago-buarqque** [comment]
ci:stop

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Review by ethib137 — APPROVED** [review]
LGTM, thanks.

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
