### PR TITLE
LPD-2466 Show Simulation icon in small screens

### PR DESCRIPTION
**Pull request by SelenaAungst**
https://liferay.atlassian.net/browse/LPD-2466

Based on https://github.com/brianchandotcom/liferay-portal/pull/131881 it looks like this was the only change needed, please let me know if anything else needs to be changed.

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by pat270** [comment]
So one of the reasons the simulation icon wasn't shown in small screens is because we couldn't replicate desktop view on mobile devices. Is this a valid accessibility bug?

**Comment by ethib137** [comment]
@pat270 more functionality has been moved to that sidebar, so now it really is even more important: https://liferay.atlassian.net/browse/LPD-2466?focusedCommentId=2576585

**Comment by ethib137** [comment]
FYI... simulation panel is owned by @liferay-echo so we will need to get their approval on these changes as well.

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @SelenaAungst @ethib137 @pat270,

It looks good to us, so I'm forwarding this one.

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by SelenaAungst** [comment]
Thank you @ealonso!

**Pull request closed without merging**
