### PR TITLE
LPD-1526 fixes security bug on Language Override portlet

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Ticket [LPD-1526](https://liferay.atlassian.net/browse/LPD-1526)

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1267401_12665

**Comment by ethib137** [comment]
ci:reevaluate:1267401_12665

**Comment by ethib137** [comment]
CI failures are unrelated. LGTM.

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
