### PR TITLE
LPS-200946 Stabilize configuration framework tests

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Instance Settings tests are failing for a couple reasons. 
1. Portal settings needs to teardown first otherwise instance teardown throws a JSON null error
2. Sign in is hanging on a specific macro that is not reproducible locally. Proposal is to use other log in macros as a workaround.

**Test Plan**
- [x] `ci:test:configuration-framework` have affected Instance settings tests pass

**JIRA Ticket**
https://liferay.atlassian.net/browse/LPS-200946

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:configuration-framework:nocompile

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:configuration-framework:nocompile

**Comment by john-co** [comment]
cc/ @thiago-buarqque @ethib137 for your review. This will be one of the last major test fixes I'll make so I figure it's best to let you guys take a look and let me know if any questions so I can pass on the knowledge of poshi test maintenance while I'm still available.

**Comment by thiago-buarqque** [comment]
Hey @john-co, the changes seem fine to me.

**Comment by ethib137** [comment]
LGTM also.

**Comment by john-co** [comment]
ci:forward

**Pull request closed without merging**
