### PR TITLE
LPS-198660 Apply missing styles in cadmin for autocomplete input list

### PR DESCRIPTION
**Pull request by veroglez**
Hi guys!

This bug has been reported to the Echo team https://liferay.atlassian.net/browse/LPS-198660, where autocomplete input list styles seem to be overlapped by cadmin classes. I send you this PR where I include these styles in `clay_admin.scss`. @pat270 @marcoscv-work  could you review it?

Thanks in advance! 😄

### CODE REVIEW

**Review by pat270 — CHANGES_REQUESTED** [review]
@veroglez we are missing styles for `yui3-aclist-hidden`. I had to use Blogs, hopefully it's the same?

yu3-ac-list

**Comment by veroglez** [comment]
@pat270 yep! Thanks for realizing that! I have updated the code 😄

**Comment by ethib137** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Review by pat270 — APPROVED** [review]
LGTM, Thanks @veroglez !

**Comment by eltonccdantas** [comment]
ci:test:bundle

**Comment by eltonccdantas** [comment]
[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1698844534903&testrayRunIdA=2448879100&testrayRunIdB=2449975557)

[Tests that I ran locally](https://gist.github.com/eltonccdantas/1f975f4d307fa6bc1caef894770bc3ea)

**Pull request closed without merging**
