### PR TITLE
LPD-24385 Review & adapt tests using hard-coded test password

### PR DESCRIPTION
**Pull request by thiago-buarqque**
https://liferay.atlassian.net/browse/LPD-24385

## Context
App Sec is going to remove the value of the `default.admin.password` property permanently according to https://liferay.atlassian.net/browse/LPD-4254?focusedCommentId=2628865.

**Changes needed**

"The value to the property `default.admin.password` is going to be set blank in portal.properies and set to different value in the ci, so it is needed to change all tests that have hardcoded "test" as the value as admin's password ". Reason, we can't deliver a product setting a default admin's password and we want to avoid the customer use "test" as password.

## Solution
Replace hard coded `test` passwords from our component with `PropsUtil.get("default.admin.password")`

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by ethib137 — APPROVED** [review]
LGTM

**Comment by thiago-buarqque** [comment]
ci:test:platform-experience-acceptance

**Comment by ethib137** [comment]
You can ignore the feature flag test failures. Those are a known issue. I'm working to migrate those to playwright.

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:platform-experience-acceptance

**Comment by thiago-buarqque** [comment]
Failures in suite `ci:test:platform-experience-acceptance` are expected as stated by Evan [here](https://github.com/liferay-platform-experience/liferay-portal/pull/594#issuecomment-2111644652). Forwarding to Brian.

**Comment by thiago-buarqque** [comment]
ci:forward

**Pull request closed without merging**
