### PR TITLE
LPS-198100 Remove no longer needed H2

### PR DESCRIPTION
**Pull request by marcoscv-work**
After removing the H2 we have a correct home validation (singed-out). even with best practices on:

image

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:frontend-ui

**Comment by john-co** [comment]
ci:test:accessibility

**Comment by john-co** [comment]
ci:test:themes

**Comment by john-co** [comment]
I don't know how relevant relevant could be. Here's a few test suites that may be more relevant for accessibility updates on frontend theme module.

**Comment by pat270** [comment]
LGTM

**Review by ethib137 — APPROVED** [review]
LGTM.

@eltonccdantas can you check the failing tests?

**Comment by eltonccdantas** [comment]
ci:test:bundle

**Comment by eltonccdantas** [comment]
The failures seem to be unrelated.

[Comparison run - Accessibility](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1698667534677&testrayRunIdA=2446948333&testrayRunIdB=2448237203) ✅ 

[Comparison run - Themes](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1698667902180&testrayRunIdA=2446948333&testrayRunIdB=2448235138) ✅ 

[Comparison run - Relevant](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1698668142390&testrayRunIdA=2446948333&testrayRunIdB=2448122409) ✅ 


[Frontend UI](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2448176520) ✅

**Comment by eltonccdantas** [comment]
ci:test:stable

**Comment by eltonccdantas** [comment]
ci:forward:force

**Pull request closed without merging**
