### PR TITLE
LPD-37456 - The product menu is rendered for certain users even when it is not open.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-37456

The logic in the if statement was wrong. What we want to do is check if the product menu is open first, then also ensure that the treeview is not supposed to be visible. Only if both those things are true should we render the product menu dom.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Review by thiago-buarqque — APPROVED** [review]
LGTM! Thanks Evan

**Review by pat270 — APPROVED** [review]

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
