### PR TITLE
LPD-30904 Remove uses of shadow-none on links and buttons for keyboar…

### PR DESCRIPTION
**Pull request by pat270**
…d accessibility

https://liferay.atlassian.net/browse/LPD-30904

This pr doesn't remove `shadow-none` from:

liferay-portal/modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/claims/pages/ClaimsTable/index.tsx

liferay-portal/modules/apps/site-initializer/site-initializer-raylife-ap/extra/remote-app/src/routes/policies/pages/PoliciesTable/index.tsx

liferay-portal/modules/apps/site-initializer/site-initializer-raylife-d2c/extra/remote-app/src/routes/get-a-quote/components/tip-container-modal/index.js

We should have the team that owns it make the changes. There might be more theme changes needed.

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
@pat270 this looks fine to me, but please have someone from search review this so they are aware of the changes. 

cc: @lipusz

**Comment by oliv-yu** [comment]
LGMT, thanks @pat270! 💯

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
