### PR TITLE
LPD-4681 Convert h5 elements to use div.h5

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPD-4681

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:report:2566707846

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
These failures are also unrelated.

**Comment by ethib137** [comment]
@pat270 same thing here... we shouldn't be making changes to anything in the workspaces directory.

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Failures look unrelated. LGTM.

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
