### PR TITLE
LPD-36494 add playwright test to the language client extension

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Coming from https://github.com/liferay-platform-experience/liferay-portal/pull/754 and https://github.com/kenjiheigel/liferay-portal/pull/1752

# Original description

[Brian asked](https://github.com/brianchandotcom/liferay-portal/pull/155009#issuecomment-2405637671) to add a playwright test for the language cx and to rewrite the README file.

1. Brian [changed the sample example](https://github.com/brianchandotcom/liferay-portal/commit/3d88785aa6b2b6abef2e3bf4b6560b6c3c11a7e0) by adding three translations: `es_AR`, `ja_JP` and `pt_BR`. The languages es and pt have variations (`es_AR`, `es_ES`, `pt_PT` etc). When the `buildLang` task runs, it identify that `es_AR` and `pt_BR` are variations and copy that value to all variations of that language.

**Example:**

Language_pt_BR.properties
```properties
my-key=Minha chave
```

when I run `buildLang` I will get this file without the _(automatic copy)_ suffix.

Language_pt_PT.properties
```properties
my-key=Minha chave
```

This is a problem because the default instance of Liferay doesn't have `pt_PT` and `es_AR` as languages available by default. So the sample deploy would fail.

2. [As requested](https://github.com/brianchandotcom/liferay-portal/commit/cfd0f7c5721a8f2e5a99b6dedd752cd8f0e2e83a), I made the README file less wordy.

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
Resent at https://github.com/liferay-platform-experience/liferay-portal/pull/760

**Comment by ethib137** [comment]
Reopening since the fix for the SF error is already in master.

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:playwright

**Review by ethib137 — APPROVED** [review]
Everything looks good to me. If we can get the necessary tests passing, then it's ready to be forwarded.

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Comment by thiago-buarqque** [comment]
ci:test:platform-experience

**Comment by thiago-buarqque** [comment]
ci:test:stable

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Comment by thiago-buarqque** [comment]
ci:report:45174963

**Comment by thiago-buarqque** [comment]
@ethib137 no related failures. Forwarding it

**Comment by thiago-buarqque** [comment]
ci:test:stable

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:forward:force

**Pull request closed without merging**
