### PR TITLE
LPD-24216 check if configuration screen is visible before adding to search result

### PR DESCRIPTION
**Pull request by thiago-buarqque**
~~Just noticed a small improvement on the `ConfigurationEntryRetriever`. Currently the client code, i.e. `SearchResultsMVCRenderCommand`, is handling the filtering for `ConfigurationScreen` by visibility and scope. Since that's the only usage of the method and getting visible `ConfigurationScreens` is the usual, I create a method for that on `ConfigurationEntryRetriever`~~

The above is over-engineering, talked to Brian, learned something new :D (when is _necessary_ to do). Removing the commit.

## Original description
=====
Context:
We are hiding some configurations using the Feature Flag, one of those configurations uses a customized screen (`com.liferay.portal.security.script.management.web.internal.configuration.admin.display.ScriptManagementConfigurationScreen`). Even if we add the Feature Flag annotation on `ScriptManagementConfiguration` class the configuration still appears when the user search for the configuration title. I noticed that this happens because the ConfigurationScreen is being considered for the search result even if it is not visible.
Let me know if more details are needed.

https://liferay.atlassian.net/issues/LPD-2419
https://liferay.atlassian.net/browse/LPD-24216

### CODE REVIEW

**Comment by linolaoj** [comment]
Hi @thiago-buarqque , @pat270 , the only way this can be seen on the screen is if we have a configuration with a customized screen like the `ScriptManagementConfiguration` that should be hidden by a feature flag. I'm not sure how you can test this since the feature flag is a temporary thing.
Thank you for reviewing this.

**Comment by ethib137** [comment]
Hey @linolaoj , in this case what you should provide is steps that include making a change to a class and redeploying the module. Then we can easily make sure we are testing the same thing you were. Thanks. 😄

**Comment by thiago-buarqque** [comment]
@linolaoj recently we had a conversation on our public channel regarding a similar issue. In that case, the configuration was still showing on the screen even with the feature flag option declared on the Configuration class. The issue was the dev forgot to implement the isEnabled method, which was making the screen show up by default. 

In your case, the scenario is not the main page that list the configurations, but the one that shows the search results. Since you have the feature flag check inside the `isVisible` method, the issue is in fact with the MVCRenderer.

**Comment by linolaoj** [comment]
Hi @ethib137, this is the configuration that we want to hide with a feature flag https://github.com/linolaoj/liferay-portal/pull/268. To check if it is appearing in the search results the user can search for `Script Management` in the `System Settings` search bar.
Let me know if more details are needed.

**Comment by thiago-buarqque** [comment]
Preview of steps

https://github.com/liferay-platform-experience/liferay-portal/assets/57292581/e6a8d9f4-46d0-4569-a1b8-8812e120078a

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:forward

**Comment by ethib137** [comment]
Thank you @linolaoj

**Pull request closed without merging**
