### PR TITLE
LPD-28766 Removes frontend-theme-font-awesome-web module

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----

As part of **Improve Build Times** initiative with **Develocity** we are analyzing the build process, and we found that **buildCSS** and **copyCSS** are not needed since we are already doing it in frontend build.

In this analysis we found that **frontend-theme-font-awesome-web** is adding some custom logic into **buildCSS** gradle task.

Taking a look into the module and investigating a little bit more, we found that this module is not used internally, and it's was added kept backwards compatibility since 7.2. We think it can be deleted from the product. So, if some customer needs it, then it could be  incorporate to their custom theme.

Screenshot 2024-06-18 at 9 20 26 AM

[Link to the ticket](https://liferay.atlassian.net/browse/LPD-28765)

Proposed Solution
-----

Removes **frontend-theme-font-awesome-web** module

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:help

**Comment by ethib137** [comment]
ci:test:themes

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
