### PR TITLE
LPD-43223 - Predefined value table is either not visible or non interactive on object Actions when Clay table FF is enabled

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-43223

The main approach here requires switching the table to a controlled component. Otherwise inline editable cells will not work correctly since they need to pass in the updated html that results from editing.

This also reveals another bug in the Clay Table. [This](https://github.com/liferay/clay/blob/961c6715dfbc08da721fb1b8c97033bcd450958c/packages/clay-core/src/table/Head.tsx#L75) is only called at first render, but we need this to be called every time the collection changes. This results in an extra cell added to the body rows of the table when you hide a column. This issue can be reproduced by navigating to Commerce products and hiding a column in the table. 

Screenshot 2024-12-16 at 9 11 38 PM

This is caused by the collection sizing not being updated correctly which causes [this](https://github.com/liferay/clay/blob/961c6715dfbc08da721fb1b8c97033bcd450958c/packages/clay-core/src/table/Row.tsx#L247) to evaluate to true when it shouldn't. As a result an extra cell is added to the body that is not in the header.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
> This also reveals another bug in the Clay Table. [This](https://github.com/liferay/clay/blob/961c6715dfbc08da721fb1b8c97033bcd450958c/packages/clay-core/src/table/Head.tsx#L75) is only called at first render, but we need this to be called every time the collection changes. This results in an extra cell added to the body rows of the table when you hide a column. This issue can be reproduced by navigating to Commerce products and hiding a column in the table.

@ethib137 This is a bit strange, it's happening when you hide the columns. I believe this is more of a side effect of FDS. For example, when hiding the column, this should not be reflected in the external data, for example, in the items in `<Head />`. I can't reproduce this outside of DXP.

I remember this didn't work very well because when hiding columns in FDS, the implementation was to remove the items from the data and pass them to the component rendered with Table. You don't need to do this, and it's done internally in the component without needing it. So I believe this case is not a bug, but I will send a PR to Clay to update the list of cells in the head every time the items change. This will have no side effects.

What we can also do is when activating the flag, remove a part from the FDS logic so that we don't need to do this and just save which items are visible without having to change the data.

**Comment by ethib137** [comment]
Hey @matuzalemsteles I was actually able to reproduce this issue in our first example of the Clay Table. You can see it here. In this case there is an additional problem that the data in the body is not being hidden, although the column in the head is.


https://github.com/user-attachments/assets/aa099a54-713f-4a81-a587-66aa3bcec236

**Comment by matuzalemsteles** [comment]
@ethib137 As I commented on Clay's PR, I now understand the problem... it has already been fixed, as soon as it is merged I will cut a release and send the update.

**Comment by ethib137** [comment]
@matuzalemsteles are any changes needed in this PR, or is this ready to be sent to frontend infra for review?

**Comment by ethib137** [comment]
Resent to https://github.com/liferay-frontend/liferay-portal/pull/4625

**Pull request closed without merging**
