### PR TITLE
LPD-39260 Update user-icon colors to new color palette

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPD-39260

user-icon

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:platform-experience

**Comment by SelenaAungst** [comment]
I am not sure if there is a way to confirm the change in the portal, as when you inspect element it just shows the hex color code. I can confirm though all 10 colors show up for users and I don't see any related errors.

**Comment by matuzalemsteles** [comment]
ci:test:platform-experience

**Review by matuzalemsteles — APPROVED** [review]

**Comment by ethib137** [comment]
LGTM

**Comment by ethib137** [comment]
ci:forward

**Comment by pat270** [comment]
ci:forward:force

**Pull request closed without merging**
