### PR TITLE
LPD-39435

### PR DESCRIPTION
**Pull request by SelenaAungst**
[LPD-39435](https://liferay.atlassian.net/browse/LPD-39435) Add twitter-x icons to Commerce themes Speedwell and Minium

I am not sure if this is the right way to fix this, or if there was something with Clay that needed to be changed, but this icon was not showing up for Speedwell or Minium themes, but showed up for all other themes.

@pat270

### CODE REVIEW

**Comment by pat270** [comment]
@SelenaAungst this is the correct way to fix it. They are overwriting Clay's icons.svg with their own.

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:platform-experience

**Comment by SelenaAungst** [comment]
Thanks @pat270! I think we are waiting on the Commerce team now to decide if we should merge this https://liferay.slack.com/archives/C4SAM7Q9Z/p1729068321966049

**Comment by ethib137** [comment]
ci:forward

**Comment by ethib137** [comment]
ci:report:44377609

**Comment by ethib137** [comment]
No unique failures... going to force forward.

**Comment by ethib137** [comment]
ci:test:stable

**Comment by ethib137** [comment]
ci:report:45851812

**Comment by ethib137** [comment]
no unique failures. Will force forward.

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
