### PR TITLE
LPD-39638 Update packages `@clayui/*` to v3.121.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Features

-   **@clayui/core:** Update sorting icons for the Clay Table. ([ac89778](https://github.com/liferay/clay/commit/ac8977871220ab1bdad2ea81fd54a7f25943f19a))
-   **@clayui/css:** LPD-39299 Adds d4-l1 for colors ([083c268](https://github.com/liferay/clay/commit/083c268c6113425790efa92fb121e0d9d7a22fd4))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:commerce

**Comment by matuzalemsteles** [comment]
How strange, looking at the log I don't see the error from the `frontend-theme-dialect` module and apparently the command has no error output.

```
     [exec] [01:29:01] Starting 'build:fix-url-functions'...
     [exec] [01:29:01] Finished 'build:fix-url-functions' after 28 ms
     [exec] [01:29:01] Starting 'build:move-compiled-css'...
     [exec] [01:29:01] Finished 'build:move-compiled-css' after 230 ms
     [exec] [01:29:01] Starting 'build:remove-old-css-dir'...
     [exec] [01:29:01] Finished 'build:remove-old-css-dir' after 12 ms
     [exec] [01:29:01] Starting 'build:fix-at-directives'...
     [exec] [01:29:01] Finished 'build:fix-at-directives' after 6.98 ms
     [exec] [01:29:01] Starting 'build:r2'...
     [exec] [01:29:01] Finished 'build:r2' after 105 ms
     [exec] [01:29:01] Starting 'build:copy:fontAwesome'...
     [exec] [01:29:01] Finished 'build:copy:fontAwesome' after 170 μs
     [exec] [01:29:01] Starting 'build:minify:js'...
     [exec] [01:29:01] Finished 'build:minify:js' after 93 ms
     [exec] [01:29:01] Starting 'build:war'...
     [exec] [01:29:01] Starting 'plugin:version'...
     [exec] [01:29:01] Finished 'plugin:version' after 574 μs
     [exec] [01:29:01] Starting 'plugin:war'...
     [exec] [01:29:02] Finished 'plugin:war' after 744 ms
     [exec] [01:29:02] Finished 'build:war' after 745 ms
     [exec] [01:29:02] Finished 'build' after 23 s
     [exec] Done in 23.63s.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:frontend-theme:frontend-theme-dialect:packageRunBuild'.
```

I'm also not able to reproduce this failure locally, @ethib137, can you?

**Comment by matuzalemsteles** [comment]
Oh now I realized that the error in the console is actually above the command execution which is strange.

```
  [exec] [01:28:41] [31mError[39m in plugin "[36msass[39m"
     [exec] Message:
     [exec]     build/_css/dialect/variables/_forms.scss
     [exec] Error: Undefined variable.
     [exec]    ╷
     [exec] 80 │                     $form-control-label-size,
     [exec]    │                     ^^^^^^^^^^^^^^^^^^^^^^^^
     [exec]    ╵
     [exec]   build/_css/dialect/variables/_forms.scss 80:6  @import
     [exec]   build/_css/dialect/_clay_variables.scss 8:9    @import
     [exec]   build/_css/_clay_variables.scss 5:9            @import
     [exec]   build/_css/clay/atlas.scss 7:9                 @import
     [exec]   build/_css/clay.scss 1:9                       root styl
```

**Comment by matuzalemsteles** [comment]
@ethib137 Do you have any idea why this might be failing? talking to @pat270 it seems like it's not a problem on Clay's side but it's also confusing that we can't identify how dialect is importing the Clay variables as well as we're not selling `_classic_clay_variables.scss` but it's being imported, I'm assuming maybe this is generated at build time. Can you help us with this here?

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:commerce

**Comment by matuzalemsteles** [comment]
ci:test:platform-experience

**Comment by ethib137** [comment]
> @ethib137 Do you have any idea why this might be failing? talking to @pat270 it seems like it's not a problem on Clay's side but it's also confusing that we can't identify how dialect is importing the Clay variables as well as we're not selling `_classic_clay_variables.scss` but it's being imported, I'm assuming maybe this is generated at build time. Can you help us with this here?

Hey @matuzalemsteles , yes. Dialect has a [custom build process](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme/frontend-theme-dialect/build.gradle#L17) that copies files from Classic. Part of that is changing the name of the clay_variables file in classic to classic_clay_variables so that Dialect can add it's own clay variables too.

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
I'm really not sure why it would be breaking though. It doesn't seem like it should be related to the clay release since that variable is still available in clay.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:report:51850210

**Comment by ethib137** [comment]
ci:test:commerce

**Comment by ethib137** [comment]
ci:test:platform-experience

**Comment by ethib137** [comment]
ci:report:52148341

**Comment by matuzalemsteles** [comment]
@ethib137 Apparently the tests seem unrelated, some of the commerce tests seem to be related to the modal, but I don't think that's related to this release.

Regarding the bug with variables, talking to Patrick, the bug was that he was using the variable without interpolation, which was causing the bug. The strangest thing is that apparently this never worked, but now this error has occurred. Maybe it's a version of node-sass, but Patrick has fixed it now.

**Comment by ethib137** [comment]
ci:test:commerce

**Comment by matuzalemsteles** [comment]
@ethib137 looking at the errors from the single tests they seem unrelated to this PR.

**Comment by ethib137** [comment]
ci:report:54281830

**Comment by ethib137** [comment]
Yep, the failing tests seem unrelated. I'm going to forward.

**Comment by ethib137** [comment]
ci:forward:force

**Comment by matuzalemsteles** [comment]
I will fix the conflict.

**Comment by matuzalemsteles** [comment]
ci:forward:force

**Comment by matuzalemsteles** [comment]
ci:forward:force

**Comment by ethib137** [comment]
ci:stop

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:stop

**Comment by ethib137** [comment]
ci:stop

**Comment by ethib137** [comment]
ci:forward:force

**Comment by ethib137** [comment]
ci:forward:force

**Comment by ethib137** [comment]
@matuzalemsteles there's a rebase error now... would you mind rebasing and then we can forward?

**Comment by matuzalemsteles** [comment]
ci:forward:force

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
