### PR TITLE
LPD-15319 Add visibility property to contextual sidebar

### PR DESCRIPTION
**Pull request by veroglez**
Hi guys! 

I'm sending you the fix for this issue https://liferay.atlassian.net/browse/LPD-15319. It's an issue found in the Web Content panel but it corresponds to the contextual sidebar css. @pat270 could you take a look? 

Thanks in advance! :smile:

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:stable

**Comment by ethib137** [comment]
FYI... All failures look unrelated. @pat270 if the changes look fine to you, please feel free to forward this. Thanks @veroglez !

**Comment by pat270** [comment]
LGTM

**Comment by pat270** [comment]
ci:forward:force

**Pull request closed without merging**
