### PR TITLE
LPD-17672 clay:select tag should output a for attribute on label

### PR DESCRIPTION
**Pull request by pat270**
- when `clay:select` has an `id` attribute and `label`, it should output a `for`
      attribute on the `label` with the value of the `id`. It associates the `label`
      with the form element.

LPD-17672 Clay Sample add unique id's to form elements

https://liferay.atlassian.net/browse/LPD-17672

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Thanks @pat270 . Can you send this PR to @liferay-frontend instead since they own this component.

**Comment by pat270** [comment]
ci:test:stop

**Comment by pat270** [comment]
Resent at https://github.com/liferay-frontend/liferay-portal/pull/4011

**Pull request closed without merging**
