### PR TITLE
LPS-201892

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**
# Motivation

Right now there is no way to clean mail fields since the blank value is consider an obfuscated value and no action is performed over the PortletPreferences.

**Steps to Reproduce:**

1. Access Instance Settings > Email >Mail Settings and change Outgoing port to 123
2. Access again Instance Settings > Email > Mail Settings and try to leave that field blank.

**Expected Results:**
The field can be saved with a blank value

**Current Results:**
The value 123 doesn’t get deleted.

# Proposed Solution
Right now blank is the default value when the properties need to be obfuscated. The reason to do this is to avoid providing specific configuration details, specially for LXC environments, see [LPS-163793](https://liferay.atlassian.net/browse/LPS-163793)

So the idea is to reset preferences at the backend when a null/empty value is received.

A blank value can mean two things:
 * The user hasn't changed the "obfuscated" value, so the preferences can be reset because that means that the default (system setting or portal.properties) will be used.
 * The user introduced previously a value, saved it, and know wants to remove it to use the default value. In this case the property must be reset to reflect this change.

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @ethib137, since this pull request is sent by an external developer, would you mind reviewing it?

**Comment by pedro-michel** [comment]
Hey @marianoalvarosaiz , 

Can you please adjust this PR to fit [with this template of PR](https://github.com/liferay-platform-experience/liferay-portal/pull/328) for provide more details to the team?

**Comment by ethib137** [comment]
Hi @marianoalvarosaiz,  I updated the components on the ticket to the correct ones. Could you send the pull request to the team that owns those components? I think it would be @liferay-core-infra . Thanks.

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
Hi @ethib137 ,
 
 could you please take a look to this [comment](https://github.com/liferay-platform-experience/liferay-portal/pull/370#issuecomment-1816432532)? The code is fixed at core side, but Instance Settings is the consumer. So I'm asking the review from a functional point of view. The original changes that caused this bug were introduced by the USM team, so I believe it would be better if you double check this code.

Kind regards.

**Comment by ethib137** [comment]
Hey @marianoalvarosaiz , I just took a look at your changes and it does make sense to me in light of the changes from [LPS-163793](https://liferay.atlassian.net/browse/LPS-163793). From our side this looks okay, but please send this to core infra now, since they own the code. Thank you for sending this to us, so that we could have some visibility on this change. 😄

**Comment by marianoalvarosaiz** [comment]
Thanks a lot for the review @ethib137

**Pull request closed without merging**
