### PR TITLE
LPD-22170 - Add alt property to fix accessibility issue

### PR DESCRIPTION
**Pull request by ilzamcmed**
Jira issue: https://liferay.atlassian.net/browse/LPD-22170

After I ran poshi locally, the test passed.
Screenshot_20240403_142713

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by matuzalemsteles — APPROVED** [review]
LGTM

**Comment by ilzamcmed** [comment]
ci:forward

**Pull request closed without merging**
