### PR TITLE
LPD 31478 - Theme CSS client extension is not loaded on Page with Arabic locale

### PR DESCRIPTION
**Pull request by algobob**
Ticket: https://liferay.atlassian.net/browse/LPD-31478 (LPP 54641)

## Motivation
Currently, when adding a themeCss client extension, only **main.css** and **clay.css** ( which are LTR by default ) are possible to be provided. RTL versions are automatically generated, but its broken when there are custom css properties

## Proposed Solution
This changes enable the users to provide pre-built RTL versions of **main.css** and **clay.css** in case they need.

## Steps to Verify
_Reproduction Steps:

1. Start 2024.q1.2 and deploy the attached CSS sample: "liferay-sample-theme-css-1.zip" liferay-sample-theme-css-1.zip 
2. Go to Site Builder --> Pages, click on the kebab menu on the upper right, select "Configuration". Under the "Design" scroll down until you find "Theme CSS", and click on the icon to select the CSS, and then save.
3. Go to the Home page, edit it, add a Card fragment, make sure that the Card title color is Blue, and Publish the Page.
4. On the Page URL add the Arabic locale /ar/, and enter.
5. Hard refresh the page by clicking CTRL+SHIFT+R and check the Card Title Color.

Actual Result: The Card title color does not remain blue, the color is reset to the default. The CSS is not inserted.

Expected Result: The Card title color should remain Blue._

## Screenshots/videos (if applies)
Attached on ticket

## Alternative Solutions that were discarded (if applies)
Are there other solutions that you considered or tried? If so, tell us why you decided to discard them.

## General checklist (just for reference)

- [ x ] I have considered breaking this PR into smaller PRs if the amount of changed code is too large.
- [ x ] I have performed a self-review of my own code following Liferay's code conventions.
- [ x ] I have added at least one test that proves my fix is effective or that my feature works.

### CODE REVIEW

**Comment by ethib137** [comment]
> The following guidelines have been set by the owner of this repository:
> 
> * "Thank you for sending this PR to liferay-platform-experience. If you haven't already, take this opportunity to review our [pull request guidelines](https://liferay.atlassian.net/wiki/spaces/PEDS/pages/2915598365). For additional help, please reach out via the [appropriate channels](https://liferay.atlassian.net/wiki/spaces/PEDS/overview#%3Aslack%3A-Slack-Channels)."

Thanks @algobob ! Please update the PR following the PR guidelines explained above.

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:relevant

**Review by ethib137 — CHANGES_REQUESTED** [review]
Hey Anderson, thanks for your work on this.

As part of this we should also be updating the themeCSS samples to include the RTL properties. 

In each `client-extension.yaml` add:
```
clayRTLURL: css/clay_rtl.css
mainRTLURL: css/main_rtl.css
```

**Comment by algobob** [comment]
> Hey Anderson, thanks for your work on this.
> 
> As part of this we should also be updating the themeCSS samples to include the RTL properties.
> 
> In each `client-extension.yaml` add:
> 
> ```
> clayRTLURL: css/clay_rtl.css
> mainRTLURL: css/main_rtl.css
> ```

you mean the 3 themecss sample repo inside `liferay/workspaces` folder?

**Comment by ethib137** [comment]
> > Hey Anderson, thanks for your work on this.
> > As part of this we should also be updating the themeCSS samples to include the RTL properties.
> > In each `client-extension.yaml` add:
> > ```
> > clayRTLURL: css/clay_rtl.css
> > mainRTLURL: css/main_rtl.css
> > ```
> 
> you mean the 3 themecss sample repo inside `liferay/workspaces` folder?

Yes 😄

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:relevant

**Review by thiago-buarqque — APPROVED** [review]
Nice! LGTM :rocket: 

Please, remove the PR from draft and send to Brian `ci:forward`

**Comment by algobob** [comment]
ci:forward

**Pull request closed without merging**
