### PR TITLE
LPS-196350 - log error when checking for a feature flag that is not present in the specified scope

### PR DESCRIPTION
**Pull request by ethib137**
Reopening from https://github.com/liferay-platform-experience/liferay-portal/pull/336 because CI isn't working.

Original Message:

The https://github.com/liferay-peds/liferay-portal/pull/277 was opened for a month, lots of changes by other teams and CI errors. This one is a cleaner version.

Story ticket: [LPS-196350](https://liferay.atlassian.net/browse/LPS-196350)

Goal
Ensure that developers understand the specific scope of the feature flag they are checking when using FeatureFlagManagerUtil.isEnabled("LPS-xxx"). If it's not possible to find the feature flag, they should pass the companyId or set it in the CompanyThreadLocal. It's important to avoid checking for an instance-scoped feature flag in the system-level FeatureFlagsBag, and vice versa. This helps prevent confusion and ensures accurate evaluation of feature flags within the intended scope.

Proposed Solution
Log an error message warning that the Feature Flag is not present in the specified scope.
Add to the [docs](https://liferay.atlassian.net/wiki/spaces/ENGR/pages/1604714779/Feature+Flags) how this error occurs and how to prevent it. For instance, the text to be added to the docs is:
If you're checking for a Feature Flag status, but companyId is not available either where you're checking the Feature Flag or in CompanyThreadLocal, you should consider refactoring the check to where you have the companyId or make the Feature Flag system scoped in case you can't refactor the code (refer to the System Feature Flags for more details).

Feature flags I catch along the way
LPS-183661:
Occurred at: ElasticsearchIndexWriter.java:407, CompanyIndexFactory.java:63 and CompanyIndexFactoryHelper.java:98)
Approach: [recently removed by Yu](https://github.com/liferay/liferay-portal/commit/25c769ba6f6598491fd14065c2f03d69aaed77cd)
COMMERCE-9410
Occurred at: CommerceOrderInfoItemCapabilitiesProvider.java:30,  
Approach: [@Danny Situ](https://liferay.slack.com/team/UFN5ER96X) said it makes sense to be turned into system scoped
LPS-180198
Occurred at: MembershipsUserFieldExpressionHandlerRegistrator.java
Approach: [@Stian Sigvartsen](https://liferay.slack.com/team/U04TD8UQ3) said it was okay to be turned into system scoped
LPS-180328
Approach: passed companyId LayoutImpl.java:1521
LPS-157670
Approach: is used on StartupHelperUtil:121 to upgrade the portal, so it's system scoped
LPS-184255
Approach: passed companyId com.liferay.journal.web.internal.model.listener.DDMStructureModelListener.java:41
LRAC-10632
Occurred at: BaseModelListener.java:56
Approach: [@Marcellus Tavares](https://liferay.slack.com/team/U04CWP1ER) said it should be system scoped
LPS-195205
Approach: passed companyId in LayoutLocalServiceImpl.java:239
LPS-174816
Approach: passed companyId in StoreAreaAwareStoreWrapper.java:222
LPS-122920
Approach: passed companyId in BaseTextEmbeddingModelDocumentContributor.java:153
LPS-180328
Approach: passed companyId in com.liferay.layout.content.page.editor.web.internal.model.listener.LayoutModelListener:28

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1277401_10516

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
@eltonccdantas Can you take a look at the failing tests?

**Comment by ethib137** [comment]
@drewbrokke Do you see any changes needed?

**Comment by ethib137** [comment]
@eltonccdantas if failures are unrelated and @drewbrokke approves this can you forward it?

**Comment by eltonccdantas** [comment]
> @eltonccdantas if failures are unrelated and @drewbrokke approves this can you forward it?

Sure...

**Comment by eltonccdantas** [comment]
Due to the amount of aborted tests, I'll trigger `relevant` again.

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by eltonccdantas** [comment]
> LGTM 👍

Thanks @drewbrokke , I'll take some time to analyze the failures and if everything is okay I'll forward this one.

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:test:bundle

**Comment by ethib137** [comment]
@eltonccdantas , how's this one looking? Is it ready to be forwarded?

**Comment by eltonccdantas** [comment]
> @eltonccdantas , how's this one looking? Is it ready to be forwarded?

I triggered `ci:test:bundle` in order to test it locally, since every try we had in `relevant` carries `Build was aborted` in some tests. I'll jump on it now! 🕵🏻

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Hey @ethib137 , I tried to reproduce the tests in that [comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2448156888&testrayRunIdA=2448879100&statusB=3) but all [the integration tests failed](https://gist.github.com/eltonccdantas/cc0cd87ec12d2a6007f9a7aad85c0eb1) and some Poshi tests as well. Let's wait for this new `relevant` run I triggered for another analysis.

**Comment by thiago-buarqque** [comment]
Hey @eltonccdantas and @ethib137, I'm back from my medical leave. The CI has failures that I have to take care of. Someone introduced something new since last time I saw the PR (again haha)

**Comment by eltonccdantas** [comment]
Alright @thiago-buarqque, let me know if you need any help.

**Comment by thiago-buarqque** [comment]
@eltonccdantas, the issue seems to be fixed. I took a look at the CI results and seems that the errors are unrelated. There a lot tests that failed to run but they aren't related to my changes (other recent PRs also have the errors). I can ensure that errors related to my changes WILL have a message like.

> Feature flag LPS-XXX is not available for company 1234

Do you have some time to take a look to see if I missed something?

**Comment by eltonccdantas** [comment]
Hey @thiago-buarqque, I am concerned about [that test](https://testray.liferay.com/home/-/testray/case_results/2449967061) and [that one](https://testray.liferay.com/home/-/testray/case_results/2449967044) concerning `Content Pages`, would you be able to take a closer look?



[Comparison run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2449963618&testrayRunIdA=2448879100&statusB=3)

**Comment by thiago-buarqque** [comment]
@eltonccdantas there was indeed an error in my branch. It was caused by the fact that we now have system scoped FFs and in this PR I'm passing the companyId (which wasn't before) in some FFs checks. It was a subtle error hard to track. Thanks for your help.

**Comment by thiago-buarqque** [comment]
A conflict was introduced in master and I added a new commit for the issue mentioned above, so this is the new [PR](https://github.com/liferay-platform-experience/liferay-portal/pull/353).

**Pull request closed without merging**
