### PR TITLE
LPD-26624 - Modify CSS for corrected input-localized markup order

### PR DESCRIPTION
**Pull request by SelenaAungst**
Ticket: https://liferay.atlassian.net/browse/LPD-26624

## Motivation
When the user tries to navigate through the following component using the Tab key, the focus is inverted compared to the order of elements:
image

To allow for the correct focus order, we should swap these elements:
image

## Proposed Solution
Remove the CSS responsible for this visual change in template-web, journal-web, and document-library web to make this change only in those locations. 

## Steps to Verify

This change is visible in 3 locations:

Web Content:
1. Navigate to Content & Data > Web Content > Web Content.
2. Create a new Basic Web Content Article.

Template:
1. Navigate to Content & Data > Web Content > Templates.
2. Create a new Template.

Documents & Media:
1. Navigate to Content & Data > Documents & Media > Document Types.
2. Create a new Document Type.

All:

   3. Click the Control Menu at the top of the page, then use the tab key to navigate to the Language Selector and Title input field.
   4. Observe focus order.

## Screenshots
document_LPD-26624
template_LPD-26624
web_content_LPD-26624

## Alternative Solutions that were discarded
We attempted to swap these elements only in the markup and preserve their order visually, but this caused unintended consequences in other locations. This discarded solution can be found here: https://github.com/liferay-platform-experience/liferay-portal/pull/637

### CODE REVIEW

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:content-management

**Comment by SelenaAungst** [comment]
ci:test:data-engine

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:report:19562547

**Comment by ethib137** [comment]
ci:report:19596304

**Comment by ethib137** [comment]
@SelenaAungst can you also provide a screen shot of web-content with FF LPS-114700 enabled, so we can ensure nothing is breaking there?

**Comment by SelenaAungst** [comment]
Hi @ethib137,
I tested using the feature flag and this page looks the same with and without the changes.
image

**Comment by SelenaAungst** [comment]
It looks like these relevant tests need to be updated:
https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1026398/testReport/com.liferay.journal.internal.search.spi.model.index.contributor.test/JournalArticleModelDocumentContributorTest/

I will update this then look into the failures from content-management and data-engine.

**Comment by SelenaAungst** [comment]
It looks like these failing tests were added [only a few days ago](https://github.com/liferay-content-management/liferay-portal/pull/5577), so I am working to make sure they are updated correctly.

**Comment by SelenaAungst** [comment]
@ethib137 After looking through the test reports, it does not look like any of the failures are caused by my changes.

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
