### PR TITLE
LPD-7010 (follow up) Read and validate script element attributes from UI client extension

### PR DESCRIPTION
**Pull request by ethib137**
Resent from: https://github.com/liferay-platform-experience/liferay-portal/pull/529

@thiago-buarqque 
_Original Description:_

Adding the validation for scriptElementAttributesJSON field coming from the Frontend.

I updated the way FE receives the attributes, it was expecting an array, but the data is stored as JSON string and it doesn't make sense for the BE to translate it to an array and send to the FE.
I also found two issues on the FE:
It was sending an empty object {} when the attributes were empty, it should send an empty string
An boolean with false value was being translated to String due to [this](https://github.com/liferay-platform-experience/liferay-portal/pull/529/files#diff-c025c4b1e4ac02274998fbdd17f17a7a03acdb88ea20098f96dc71808d8e495cR137)

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:playwright

**Review by thiago-buarqque — APPROVED** [review]
LGTM! :rocket:

**Comment by ilzamcmed** [comment]
Thanks @ethib137! :rocket:

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
