### PR TITLE
LPD-35557 - Rename search function for document library

### PR DESCRIPTION
**Pull request by ilzamcmed**
This pull request aims to ensure consistent function naming across the Playwright files. Previously, there were instances where `search` was used in some places while `searchFor` was used in others.

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
Hey @ethib137, this PR was approved by the content management team.

**Comment by ilzamcmed** [comment]
ci:stop

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:forward

**Pull request closed without merging**
