### PR TITLE
Lpd 35069 2

### PR DESCRIPTION
**Pull request by algobob**
Continuation from #723 

Ticket: https://liferay.atlassian.net/browse/LPD-35069

## Motivation
Provides a list with all frontend token definitions ( both themes/themeCss client extensions) for the company.

## Proposed Solution
Currently its not possible to choose a specific frontend token definition because it is strictly related with the applied theme. This solution will enable this ability on backend.

## Steps to Verify
1. `Design` -> `Style Books` - `New`

### CODE REVIEW

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:relevant

**Review by thiago-buarqque — APPROVED** [review]
LGTM :rocket:

**Comment by algobob** [comment]
ci:forward

**Pull request closed without merging**
