### PR TITLE
LPD-18893 remove feature flag

### PR DESCRIPTION
**Pull request by thiago-buarqque**
https://liferay.atlassian.net/browse/LPD-18893

Removing feature flag for [Allow to modify the default token definition with the Theme CSS CX](https://liferay.atlassian.net/browse/LPD-10773). This was discussed on the daily today and you can follow the slack discussion [here](https://liferay.slack.com/archives/C04A7NLM7L1/p1714416812254769?thread_ts=1713791157.522209&cid=C04A7NLM7L1).

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:reevaluate:1347401_6188

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
Based on the [CI comparison](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1714645781991&testrayRunIdA=2565032823&testrayRunIdB=2564889491) against master, the errors are unrelated. Forwarding to Brian.

**Pull request closed without merging**
