### PR TITLE
LPD-27222 remove feature flag

### PR DESCRIPTION
**Pull request by thiago-buarqque**

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:platform-experience

**Comment by thiago-buarqque** [comment]
@ethib137 Is this one good to go?

**Comment by ethib137** [comment]
Thanks, please send to BPM.

**Comment by thiago-buarqque** [comment]
Sent here https://github.com/liferay-bpm/liferay-portal/pull/3918

**Pull request closed without merging**
