### PR TITLE
LPS-196350 - log error when checking for a feature flag that is not present in the specified scope

### PR DESCRIPTION
**Pull request by thiago-buarqque**
> Regarding the last commit: there was an error caused by the fact that we now have system scoped FFs and in this PR I'm passing the companyId (which wasn't before) in some FFs checks. It was a subtle error hard to track.

The [original PR](https://github.com/liferay-peds/liferay-portal/pull/277) was opened for a month, lots of changes by other teams and CI errors. This one is a cleaner version.

Story ticket: [LPS-196350](https://liferay.atlassian.net/browse/LPS-196350)

Goal
=======
Ensure that developers understand the specific scope of the feature flag they are checking when using `FeatureFlagManagerUtil.isEnabled("LPS-xxx")`. If it's not possible to find the feature flag, they should pass the `companyId` or set it in the `CompanyThreadLocal`. It's important to avoid checking for an instance-scoped feature flag in the system-level FeatureFlagsBag, and vice versa. This helps prevent confusion and ensures accurate evaluation of feature flags within the intended scope.

Proposed Solution
========
1. Log an error message warning that the Feature Flag is not present in the specified scope.
2. Add to the [docs](https://liferay.atlassian.net/wiki/spaces/ENGR/pages/1604714779/Feature+Flags) how this error occurs and how to prevent it. For instance, the text to be added to the docs is:

> If you're checking for a Feature Flag status, but companyId is not available either where you're checking the Feature Flag or in CompanyThreadLocal, you should consider refactoring the check to where you have the companyId or make the Feature Flag system scoped in case you can't refactor the code (refer to the System Feature Flags for more details).

Feature flags I catch along the way
========
- LPS-183661:
    - Occurred at: `ElasticsearchIndexWriter.java:407`, `CompanyIndexFactory.java:63` and `CompanyIndexFactoryHelper.java:98`) 
    - Approach: [recently removed by Yu](https://github.com/liferay/liferay-portal/commit/25c769ba6f6598491fd14065c2f03d69aaed77cd)
- COMMERCE-9410 
    - Occurred at: `CommerceOrderInfoItemCapabilitiesProvider.java:30`,  
    - Approach: [@Danny Situ](https://liferay.slack.com/team/UFN5ER96X) said it makes sense to be turned into system scoped
- LPS-180198 
    - Occurred at: `MembershipsUserFieldExpressionHandlerRegistrator.java`
    - Approach: [@Stian Sigvartsen](https://liferay.slack.com/team/U04TD8UQ3) said it was okay to be turned into system scoped
- LPS-180328 
    - Approach: passed companyId `LayoutImpl.java:1521`
- LPS-157670 
    - Approach: is used on `StartupHelperUtil:121`  to upgrade the portal, so it's system scoped
- LPS-184255 
    - Approach: passed companyId `com.liferay.journal.web.internal.model.listener.DDMStructureModelListener.java:41`
- LRAC-10632
    - Occurred at: `BaseModelListener.java:56`
    - Approach: [@Marcellus Tavares](https://liferay.slack.com/team/U04CWP1ER) said it should be system scoped
- LPS-195205 
    - Approach: passed companyId in `LayoutLocalServiceImpl.java:239`
- LPS-174816 
    - Approach: passed companyId in `StoreAreaAwareStoreWrapper.java:222`
- LPS-122920 
    - Approach: passed companyId in `BaseTextEmbeddingModelDocumentContributor.java:153`
- LPS-180328
    - Approach: passed companyId in `com.liferay.layout.content.page.editor.web.internal.model.listener.LayoutModelListener:28`

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:reevaluate:1337401_4598

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
Due to the amount of aborted tests and failures, let's trigger `relevant` again.

**Comment by eltonccdantas** [comment]
ci:test:relevant

**Comment by eltonccdantas** [comment]
ci:stop

**Comment by eltonccdantas** [comment]
ci:stop:relevant

**Comment by eltonccdantas** [comment]
ci:stop:stable

**Comment by thiago-buarqque** [comment]
The feature flag LRAC-14771 [was just introduced](https://github.com/liferay-platform-experience/liferay-portal/blob/master/modules/apps/analytics/analytics-machine-learning-impl/src/main/java/com/liferay/analytics/machine/learning/internal/search/instance/lifecycle/RecommendationIndexerPortalInstanceLifecycleListener.java#L76) and is being checked without using the FeatureFlagManagerUtil, so it's giving a lot of failures. I talkes to the Analytics Cloud team to address that, also the FFs seems to be system scoped. As soon as I get an answer for that I'll update the PR with the proper changes.

**Comment by eltonccdantas** [comment]
Hey @thiago-buarqque, I'm almost at EOD, if you need anything QA related please reach out to @john-co.

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
Hey @john-co, I checked the CI results and here is what I found:

[Run comparison against master](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2452159025&testrayRunIdA=2451955445&statusB=3)

The commerce tests seem to be flaky. They have failed a couple of time in the last 4 days by the same reason. Also, I checked the jenkins logs and the errors relates to a missing type on the database schema (which means that something is wrong on the database)
> java.lang.AssertionError: Thread Thread[http-nio-8080-exec-1,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.servlet.filters.authverifier.AuthVerifierFilter, message=graphql.AssertException: type AccountGroup not found in schema

Regarding the tests not related to commerce, the only that did not seem flake is [this one](https://testray.liferay.com/home/-/testray/case_results/2452161796?tab=history). But I rebase my branch with master and ran the test locally, it's working fine.
```
com.liferay.dispatch.talend.web.internal.executor.test.TalendDispatchTaskExecutorTest > testExecute STARTED
com.liferay.dispatch.talend.web.internal.executor.test.TalendDispatchTaskExecutorTest > testExecute PASSED
```

The other tests for sure are flaky.

Could you please validate my thoughts and see if I'm missing something?

**Comment by john-co** [comment]
Just started reviewing... :hourglass_flowing_sand:

**Comment by thiago-buarqque** [comment]
Thank you @john-co. Forwarding...

**Comment by thiago-buarqque** [comment]
ci:foward:force

**Comment by thiago-buarqque** [comment]
ci:forward:force

**Comment by thiago-buarqque** [comment]
Forward is failing, sending manually...

**Comment by thiago-buarqque** [comment]
Sent manually to Brian in [#143232](https://github.com/brianchandotcom/liferay-portal/pull/143232)

**Comment by pyoo47** [comment]
I'm using this closed pull request to test some changes to `ci:forward`. Please ignore any unusual looking comments.

**Comment by pyoo47** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:close

**Pull request closed without merging**
