### PR TITLE
LPD-18882 remove feature flag

### PR DESCRIPTION
**Pull request by thiago-buarqque**
https://liferay.atlassian.net/browse/LPD-18882

Removing feature flag for epic [Configure JS Client Extensions with Script Attributes](https://liferay.atlassian.net/browse/LPD-10981)

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Comment by thiago-buarqque** [comment]
ci:stop

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by algobob — APPROVED** [review]

**Comment by thiago-buarqque** [comment]
Unrelated CI errors, force forwarding to Brian

**Comment by thiago-buarqque** [comment]
ci:forward:force

**Pull request closed without merging**
