### PR TITLE
LPS-168791 Modals should be accessible at 400% zoom

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPS-168791

add-site-modal

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@ethib137 The failures are unrelated to the changes in this PR. A lot of the errors are path errors on tables. I rebased and am going to do another test run.

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
All failures against this PR are not unique. I'm going to force forward.

**Comment by ethib137** [comment]
ci:forward:force

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
