### PR TITLE
LPD-37649 show commerce channel panel entry if there is permission for it

### PR DESCRIPTION
**Pull request by algobob**
Ticket: https://liferay.atlassian.net/browse/LPD-37649
## Motivation
When using the left-side flyout Menu, Commerce menu is incorrectly displayed despite not having permissions.

## Proposed Solution

Check permission of commerce channel control panel entry ( override isShow() method).

## Steps to Verify
Follows steps on ticket

### CODE REVIEW

**Comment by algobob** [comment]
ci:test:sf

**Comment by ethib137** [comment]
@algobob thanks for working on this. Could you please update the PR field on the ticket linking to this PR?

Regarding the fix, why do we have to explicitly check the permission here? Most other panel apps don't seem to have this explicit permission check and are properly shown and hidden based on permissions. How do those panel apps work, and why isn't this one working in the same way?

Thanks.

**Comment by algobob** [comment]
> @algobob thanks for working on this. Could you please update the PR field on the ticket linking to this PR?
> 
> Regarding the fix, why do we have to explicitly check the permission here? Most other panel apps don't seem to have this explicit permission check and are properly shown and hidden based on permissions. How do those panel apps work, and why isn't this one working in the same way?
> 
> Thanks.

Yes, that was my last resource until friday. I tried to find a solution without have to tweak directly on the panel app class, but I got stuck. Played with the *PermissionUtil classes, but no success. But I just found CommerceChannelControlPanelEntry.java, which is tweaking the visibility already. I'll migrate code to there.

**Comment by algobob** [comment]
ci:test:sf

**Comment by algobob** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Hey @algobob , this is better since it's more shared, but my earlier questions still remain:
> Most other panel apps don't seem to have this explicit permission check and are properly shown and hidden based on permissions. How do those panel apps work, and why isn't this one working in the same way?

Is this issue only happening to one Commerce Panel app, or is this happening with others in commerce? Does it occur for any other panel apps in different categories as well?

**Comment by algobob** [comment]
> l apps in different categories as well?



> Hey @algobob , this is better since it's more shared, but my earlier questions still remain:
> 
> > Most other panel apps don't seem to have this explicit permission check and are properly shown and hidden based on permissions. How do those panel apps work, and why isn't this one working in the same way?
> 
> Is this issue only happening to one Commerce Panel app, or is this happening with others in commerce? Does it occur for any other panel apps in different categories as well?

It's only happening with this specific panel app ( Channel ). Everything else is working as expected. This issue is happening because someone created this specific class( CommerceChannelControlPanelEntry) to override the visibility and added `_portletResourcePermission.contains(
				permissionChecker, group,
				CPActionKeys.VIEW_COMMERCE_CHANNELS)`, which caused the entry to stay visible.

**Comment by algobob** [comment]
> Thanks @algobob .... so shouldn't the fix just be to remove the `@Override` of `hasAccessPermission`? Then the default permission checks would be applied. What happens when you try that?

Yes, when I remove it , it works as expected. But I dont know the context why it was added and the impact it can cause. Should I remove it anyway?

**Comment by algobob** [comment]
> Hey @algobob Yes more than likely it should be removed, but we really can't be the ones to make that decision. This actually is an issue that should be worked on by commerce. What we should be doing now is to update the LPP, switching the component to Commerce and explaining in the comments what the problem is. The LPP can then be assigned to the commerce team. It would be best if Commerce removes the the @OverRide of hasAccessPermission, but they need to confirm it doesn't break anything critical on their side.

Cool, I'll do that. Thanks!

**Comment by algobob** [comment]
ci:test:relevant

**Pull request closed without merging**
