### PR TITLE
LPD-42949 Remove duplicate assemble key

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPD-42949

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Hey @pat270 , we shouldn't be removing the contents of the second assemble step we should be adding it as another item in the first assemble block. 


Instead of this:
```
assemble:
    - from: build/buildTheme/img
      into: static/img
assemble:
    - from: build/buildTheme/images
      into: static/images
```
It should be:
```
assemble:
    - from: build/buildTheme/img
      into: static/img
    - from: build/buildTheme/images
      into: static/images
```

**Comment by pat270** [comment]
@ethib137 thanks I will update it.

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Review by ethib137 — APPROVED** [review]
LGTM, thanks.

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
