### PR TITLE
LPD-24799 - Make sure all images using imgSrcReducedMotion match imgSrc

### PR DESCRIPTION
**Pull request by ilzamcmed**
Jira issue: https://liferay.atlassian.net/browse/LPD-24799

This PR is a follow-up to ensure the path on `imgSrc` matches `imgSrcReducedMotion`.

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
Hey @matuzalemsteles  @pat270 
This PR is ready to be reviewed. 
Thanks!

**Review by matuzalemsteles — APPROVED** [review]
LGTM

**Comment by ilzamcmed** [comment]
ci:forward

**Pull request closed without merging**
