### PR TITLE
LPD-27547 - Add accessibility tests to feature flags.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-27547

This PR adds an accessibility test to feature flags using the utility provided by @veroglez .

https://playwright.dev/docs/accessibility-testing

cc: @marcoscv-work

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:playwright

**Comment by ethib137** [comment]
ci:stop

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:playwright

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
@veroglez & @sandrodw3 could you take a look?

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:playwright

**Comment by veroglez** [comment]
Nice!!! :heart_eyes: thanks for work on this!

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:playwright

**Comment by ethib137** [comment]
ci:stop

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:playwright

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
