### PR TITLE
LPD-38391 Fixes bug with fixed head without background

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Well, looking at the code, this is not actually a problem in Clay or Cadmin. They had some really strange code to create the fixed head with CSS and JS. The first item in the head does not have a background due to some strange logic they did to make the head have a fixed left margin the size of the table and then they put the first item with an absolute position. It is really confusing and I don't really understand why they did this. I believe this broke the implementation and it didn't come from Clay. I thought about redoing it, but it would take time, so I'm going simpler here and adding the background, which should fix the problem now. Thoughts?

Screenshot 2024-10-04 at 14 48 04

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Hey @matuzalemsteles ... this looks pretty good. My first thought is can we fix this by removing those extra styles? Even if it looks different than before it's worth reviewing since it's better to fix a bug by removing code rather than adding code.

**Comment by ethib137** [comment]
@pat270 Do we have a pattern of using sass variables in a context like this?

**Comment by pat270** [comment]
@ethib137 we should use `$table-head-bg` variables. I made the change and sent a new pr. I don't have push access to matu's repo. https://github.com/liferay-platform-experience/liferay-portal/pull/751

**Pull request closed without merging**
