### PR TITLE
LPS-196350 log error when checking for a feature flag that is not present in the specified scope

### PR DESCRIPTION
**Pull request by thiago-buarqque**
The [original PR](https://github.com/liferay-peds/liferay-portal/pull/277) was opened for a month, lots of changes by other teams and CI errors. This one is a cleaner version.

Story ticket: [LPS-196350](https://liferay.atlassian.net/browse/LPS-196350)

Goal
=======
Ensure that developers understand the specific scope of the feature flag they are checking when using `FeatureFlagManagerUtil.isEnabled("LPS-xxx")`. If it's not possible to find the feature flag, they should pass the `companyId` or set it in the `CompanyThreadLocal`. It's important to avoid checking for an instance-scoped feature flag in the system-level FeatureFlagsBag, and vice versa. This helps prevent confusion and ensures accurate evaluation of feature flags within the intended scope.

Proposed Solution
========
1. Log an error message warning that the Feature Flag is not present in the specified scope.
2. Add to the [docs](https://liferay.atlassian.net/wiki/spaces/ENGR/pages/1604714779/Feature+Flags) how this error occurs and how to prevent it. For instance, the text to be added to the docs is:

> If you're checking for a Feature Flag status, but companyId is not available either where you're checking the Feature Flag or in CompanyThreadLocal, you should consider refactoring the check to where you have the companyId or make the Feature Flag system scoped in case you can't refactor the code (refer to the System Feature Flags for more details).

Feature flags I catch along the way
========
- LPS-183661:
    - Occurred at: `ElasticsearchIndexWriter.java:407`, `CompanyIndexFactory.java:63` and `CompanyIndexFactoryHelper.java:98`) 
    - Approach: [recently removed by Yu](https://github.com/liferay/liferay-portal/commit/25c769ba6f6598491fd14065c2f03d69aaed77cd)
- COMMERCE-9410 
    - Occurred at: `CommerceOrderInfoItemCapabilitiesProvider.java:30`,  
    - Approach: [@Danny Situ](https://liferay.slack.com/team/UFN5ER96X) said it makes sense to be turned into system scoped
- LPS-180198 
    - Occurred at: `MembershipsUserFieldExpressionHandlerRegistrator.java`
    - Approach: [@Stian Sigvartsen](https://liferay.slack.com/team/U04TD8UQ3) said it was okay to be turned into system scoped
- LPS-180328 
    - Approach: passed companyId `LayoutImpl.java:1521`
- LPS-157670 
    - Approach: is used on `StartupHelperUtil:121`  to upgrade the portal, so it's system scoped
- LPS-184255 
    - Approach: passed companyId `com.liferay.journal.web.internal.model.listener.DDMStructureModelListener.java:41`
- LRAC-10632
    - Occurred at: `BaseModelListener.java:56`
    - Approach: [@Marcellus Tavares](https://liferay.slack.com/team/U04CWP1ER) said it should be system scoped
- LPS-195205 
    - Approach: passed companyId in `LayoutLocalServiceImpl.java:239`
- LPS-174816 
    - Approach: passed companyId in `StoreAreaAwareStoreWrapper.java:222`
- LPS-122920 
    - Approach: passed companyId in `BaseTextEmbeddingModelDocumentContributor.java:153`
- LPS-180328
    - Approach: passed companyId in `com.liferay.layout.content.page.editor.web.internal.model.listener.LayoutModelListener:28`

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
### Updates during the Product Delivery event in Spain

cc: @drewbrokke and @ethib137 

**17/10/2023**

[This](https://github.com/liferay/liferay-portal/commit/bc8ff3c40e28d949434bbd39684283662d245be0#diff-2aec3ebeb96cbc33583c163550d9948888a3d9e73decc664d825b9f51d4e681eR207) change was introduced yesterday and it checks for feature flags in a generic way. I tried retrieving the companyId from the BatchEngineUnitConfiguration and passed it for the feature flag check. I'm highlighting this because the check is generic.

**18/10/2023**

Passing the companyId doesn't work, the companyId is not set to the BatchEngineUnitConfiguration. I'll contact the owner of these changes and ask how things work and see how I can proceed. The changes were just a refactor, I contacted the owner of the feature flags to make them system scoped

**19/10/2023**

I opened [this](https://liferay.slack.com/archives/C5E1CRLJY/p1697717425376029) thread to discuss things further on. 

**20/10/2023**

[Changes were made](https://github.com/brianchandotcom/liferay-portal/pull/142486) and now it's supposed to work. I'm rebasing and running CI.

Edit: Everything is working now. Closed the [old PR](https://github.com/liferay-peds/liferay-portal/pull/277) and opened this one due the reason I explained in the there and in the description.

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1267401_11641

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:stop

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
Resent [here](https://github.com/liferay-platform-experience/liferay-portal/pull/345) due to problems with CI.

**Pull request closed without merging**
