### PR TITLE
LPD-20040 The second page during set up has incorrect spacing

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPD-20040

change-pw-fixed

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:report:2548866581

**Comment by ethib137** [comment]
LGTM, failures are unrelated.

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
