### PR TITLE
LPD-24819 Remove Feature.Flag Dropdown from Portal.Properties

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Applying SF due to issues @SelenaAungst is having on her machine. Resent from #584 

https://liferay.atlassian.net/browse/LPD-24819

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by ethib137 — APPROVED** [review]
LGTM

**Comment by ethib137** [comment]
ci:forward

**Comment by SelenaAungst** [comment]
Thanks so much @thiago-buarqque @ethib137 !

**Pull request closed without merging**
