### PR TITLE
LPD-17221 Adds inline link with text to test for color contrast

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPD-17221

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:accessibility

**Comment by pat270** [comment]
ci:test:accessibility

**Comment by pat270** [comment]
ci:test:accessibility

**Comment by pat270** [comment]
I need to change the css variable to the new color. I'm not sure why it didn't take when we changed it in Clay.

**Comment by pat270** [comment]
ci:test:accessibility

**Comment by pat270** [comment]
ci:test:accessibility

**Comment by pat270** [comment]
ci:test:accessibility

**Comment by pat270** [comment]
ci:test:accessibility

**Comment by pat270** [comment]
ci:test:accessibility

**Comment by pat270** [comment]
@ethib137 Test 2 is the only one that is relevant to us. I forgot to change the value in `frontend-token-definitions`.

axe-clear

**Comment by pat270** [comment]
ci:test:accessibility

**Comment by pat270** [comment]
ci:test:accessibility

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:stable

**Comment by pat270** [comment]
The unique failures are unrelated.

**Comment by ethib137** [comment]
LGTM

**Comment by ethib137** [comment]
ci:forward:force

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
