### PR TITLE
LPD-38229 Playwright Basic Information is role button

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPD-38229

~@ethib137 I don't think this will fix the actual issue. This should take care of the possibility of `loading-animation` disappearing too quickly that happened to me once locally. I believe the issue is from https://github.com/liferay/liferay-portal/blob/master/modules/test/playwright/tests/journal-web/pages/JournalEditTemplatePage.ts#L28-L36. ~

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by ethib137** [comment]
Thanks @pat270 have you tried to find a fix for https://github.com/liferay/liferay-portal/blob/master/modules/test/playwright/tests/journal-web/pages/JournalEditTemplatePage.ts#L28-L36

**Comment by pat270** [comment]
@ethib137 I haven't, should we fix it for them?

**Comment by ethib137** [comment]
Don’t invest too much time, but it would be good to give it a try in order
to ensure that it really is the reason our test is failing. Since none of
their tests are failing it’s still possible the issue could be something
else.



Evan Thibodeau
Team Lead, Staff Software Engineer
Platform Experience & Design Systems
Liferay
M: +971 50 198 5753
E: ***@***.***

**Comment by pat270** [comment]
@ethib137 `journal-web` was trying to get the Basic Information panel button with `role="link"`. It uses `role="button"`.

role-button

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:playwright

**Comment by ethib137** [comment]
ci:report:37231095

**Comment by ethib137** [comment]
Already fixed by https://github.com/liferay/liferay-portal/commit/7f502c342a37f1784e07dab17ea22c4d1b54c6ca

**Pull request closed without merging**
