### PR TITLE
LPD 30328 If "Enable Applications Menu" is unchecked, the disabled "Commerce" tab remains displayed

### PR DESCRIPTION
**Pull request by thiago-buarqque**
SF for #648 

LPD-30328 https://liferay.atlassian.net/browse/LPD-30328 that fixes
LPP-54582 https://liferay.atlassian.net/browse/LPP-54582

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
Please @algobob, make sure to forward this as soon the CI finishes.

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
Hey @algobob, apparently there is a failing test at `ApplicationsMenuPanelAppsMVCResourceCommand.java`

see https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/956722/testReport/com.liferay.product.navigation.applications.menu.web.internal.portlet.action.test/ApplicationsMenuPanelAppsMVCResourceCommandTest/testPanelCategories/

**Comment by algobob** [comment]
> ApplicationsMenuPanelAppsMVCResourceCommand

That's weird. All tests are passing locally. I'll re-run here

**Comment by algobob** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by ethib137 — APPROVED** [review]
LGTM

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
