### PR TITLE
LPD-23943 Update packages `@clayui/*` to v3.114.0

### PR DESCRIPTION
**Pull request by matuzalemsteles**
### Bug Fixes

-   **@clayui/core:** fixes bug when changing column visibility when there is only one column visible and disabled ([bdfcd86](https://github.com/liferay/clay/commit/bdfcd867f50b73efae4569ce3b86c18eedbcc83a))
-   **@clayui/css:** fix padding in modal footer ([feb9724](https://github.com/liferay/clay/commit/feb972477fa7a09854aa28c38762913a41d824e2))
-   **@clayui/css:** LPD-21741 c-prefers-reduced-motion should disable animation when on a parent element ([2034f5b](https://github.com/liferay/clay/commit/2034f5b06aedcde9a80485abf8691804e28afe5c))
-   **@clayui/css:** LPD-22263 remove use of fade-in function ([160152d](https://github.com/liferay/clay/commit/160152d3233b429af4543923f5680b1dbdcd483e))
-   **@clayui/css:** update footer spacing in the modal ([72a2217](https://github.com/liferay/clay/commit/72a22175bd1a25af30a7a382a66255d60d8e13e5))
-   **@clayui/css:** update footer spacing in the modal on cadmin ([35231c4](https://github.com/liferay/clay/commit/35231c499ed3d4de113ab185d7534bbe9caef5b2))
-   **@clayui/navigation-bar:** fixes navbar size bug when resizing ([42bd090](https://github.com/liferay/clay/commit/42bd090b354173234b270ce49bfba7b58431f9c5))
-   **@clayui/pagination-bar:** LPD-17368 Follow up - Add aria-label ([ba21e0e](https://github.com/liferay/clay/commit/ba21e0e1408bfe3a267c504edb21527f95cbafdb))
-   **clay-autocomplete:** Remove autocomplete async filter paginated example ([6366d29](https://github.com/liferay/clay/commit/6366d296e17be2f8aac6474951cc1728a208eca5))

### Features

-   **@clayui/card:** LPD-1261 Add ClayRadio component and its radioProps ([1960c4d](https://github.com/liferay/clay/commit/1960c4df8ac544cd7c14ee64bf57139d74f8bd73))
-   **@clayui/card:** LPD-1261 Add new radio card case in CardWithInfo stories ([188a70c](https://github.com/liferay/clay/commit/188a70c3ce54e91d50e13bbac4086fd57342397d))
-   **@clayui/card:** LPD-1261 Add radio selectable example in CardWithHorizontal story ([8e9b395](https://github.com/liferay/clay/commit/8e9b39539a278c0c8916020d035c402a419f46e9))
-   **@clayui/card:** LPD-1261 Add radio selectable example in CardWithUser story ([74a7a59](https://github.com/liferay/clay/commit/74a7a59b737a05de3ca50a07e2e6c382009c0a6e))
-   **@clayui/card:** LPD-1261 Add radio selectable to CardWithHorizontal ([5231664](https://github.com/liferay/clay/commit/52316644cba723d8d28e9809ccc3dfafa804f507))
-   **@clayui/card:** LPD-1261 Add radio selectable to CardWithUser ([8326f49](https://github.com/liferay/clay/commit/8326f49c7d7246444cc66ff0f840c2e866c15fa7))
-   **@clayui/card:** LPD-1261 Add selectableType prop to choose between checkbox and radio ([ca499f8](https://github.com/liferay/clay/commit/ca499f8524b1772b094cf7933b19261813bbdee2))
-   **@clayui/card:** LPD-1261 Add tests ([843ace6](https://github.com/liferay/clay/commit/843ace6c63d7ef8bd2ef80247e5cb0c8d2803384))
-   **@clayui/card:** LPD-1261 Add tests for ClayCardWithHorizontal ([9cd1e0a](https://github.com/liferay/clay/commit/9cd1e0a38e6722463d3d92d7486bfe105bc46e08))
-   **@clayui/card:** LPD-1261 Add tests for ClayCardWithUser ([04cc498](https://github.com/liferay/clay/commit/04cc4982bfd17b78cdbe5cf0c8638e4f4bb9b350))
-   **@clayui/card:** LPD-1261 Add truncate prop to CardWithHorizontal ([6f88188](https://github.com/liferay/clay/commit/6f88188e1065bfe5eb3081487728162249c49267))
-   **@clayui/card:** LPD-1261 Add truncate prop to CardWithUser ([43793e3](https://github.com/liferay/clay/commit/43793e368b4288e03a2bcc7c87e70fe1e6bae724))
-   **@clayui/card:** LPD-1261 Add truncate props to determine if the card text is truncated or not ([a786599](https://github.com/liferay/clay/commit/a786599314b3a59953e01592e6c1da21e5dfd604))
-   **@clayui/card:** LPD-1261 Update the thresold for clay-card ([daaf917](https://github.com/liferay/clay/commit/daaf91770e73acfd04091cb8e985fae904dbe549))
-   **@clayui/css:** LPD-21829 Adds content-shield, scim, shield-asterisk svgs ([cc51841](https://github.com/liferay/clay/commit/cc518419ced71f4d3a31dadf076ae282f9d4c6ec))
-   **@clayui/empty-state:** LPD-21741 Add new SVG empty, success and search state ([0afe5f5](https://github.com/liferay/clay/commit/0afe5f553cd309d9125fd259ec61b27c0c9b0770))
-   **@clayui/empty-state:** LPD-21741 Add reduced motion SVGs ([9e4798f](https://github.com/liferay/clay/commit/9e4798f744edbb86f0634a8e7cae4f93c483791f))
-   **@clayui/empty-state:** LPD-21741 add SVG file and change paths ([e6de535](https://github.com/liferay/clay/commit/e6de5358c45ebca7585154f7972b88e00fb9d307))
-   **@clayui/empty-state:** LPD-21741 adjusting the props name to state and removes redundancy ([d2e32a5](https://github.com/liferay/clay/commit/d2e32a5b6bc17f5e5fddc3b77e1dcfc710f863dd))
-   **@clayui/empty-state:** LPD-21741 change snapshot and update jest config ([51a31c4](https://github.com/liferay/clay/commit/51a31c4663acf6d308dc5e1afe2ffa27d4360ce1))
-   **@clayui/empty-state:** LPD-21741 Change style to include reduce motion ([da98cfa](https://github.com/liferay/clay/commit/da98cfac3a9fe54f2eaa300744af57121aeb85cb))
-   **@clayui/empty-state:** LPD-21741 Cleanup and adjustment of success SVG ([7455b58](https://github.com/liferay/clay/commit/7455b58a60bbdf3c954096076c3e622e11c3ed24))
-   **@clayui/empty-state:** LPD-21741 Cleanup and update stories ([a0a3f31](https://github.com/liferay/clay/commit/a0a3f31dcfdbdacdfc00c785cca15042a0ef7eb1))
-   **@clayui/empty-state:** LPD-21741 Move style inline, keep animations styles on Clay CSS ([d84528f](https://github.com/liferay/clay/commit/d84528f51032129b41eaf18efb68f944bea63e13))
-   **@clayui/empty-state:** LPD-21741 remove changes to the empty state component ([bb132b3](https://github.com/liferay/clay/commit/bb132b346f86f19a0cb32995cef80936bf46bf81))
-   **@clayui/empty-state:** LPD-21741 SF ([19b1a0d](https://github.com/liferay/clay/commit/19b1a0de2e8be08ae5d0abd2596b33469784c2cc))
-   **@clayui/empty-state:** LPD-21741 Update docs ([593bdd5](https://github.com/liferay/clay/commit/593bdd51a3b48f5c6bf891c33e79cba75b35e726))
-   **@clayui/empty-state:** LPD-21741 Update docs and add SVG on pathname match ([22c541b](https://github.com/liferay/clay/commit/22c541b09bf58c97b998ad982acfffd17f667f88))
-   **@clayui/empty-state:** LPD-21741 update snapshot ([40ebe8b](https://github.com/liferay/clay/commit/40ebe8b3bf67ab24da8cc90d936a7f19307f3dad))
-   **@clayui/empty-state:** LPD-21741 Update snapshots ([e03f190](https://github.com/liferay/clay/commit/e03f19010830aba90f50ad372f464433635c3720))
-   **@clayui/empty-state:** LPD-21741 Update tests, snapshots and size limit ([2d84b51](https://github.com/liferay/clay/commit/2d84b51f97c7f8187b8c88da96eccd2da7a50fba))

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:report:2562691831

**Comment by ethib137** [comment]
Hey @matuzalemsteles the relevant failures look unrelated, but the stable failures look like they might be caused by the release. It looks like the empty state component is generating a url for an svg image that does not exist.
Screenshot 2024-04-24 at 4 56 27 PM
It's looking for `no_item_reduced_motion.svg`, but [no_item.svg](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/ItemConfigurationSidebar.js#L74) is all that exists.

**Comment by matuzalemsteles** [comment]
> but the stable failures look like they might be caused by the release. It looks like the empty state component is generating a url for an svg image that does not exist.

@ethib137 Thanks for looking at this... Hmm this would actually be the expected behavior to support reduced motion to empty state, I think this already happened before because we always had this feature.

**Comment by ethib137** [comment]
So in that case we should probably be reporting this to the affected team, otherwise they likely wouldn't know to change anything.

**Comment by matuzalemsteles** [comment]
> So in that case we should probably be reporting this to the affected team, otherwise they likely wouldn't know to change anything.

Yeah, I'm going to talk to the team to report this problem but anyway we have this information in the documentation and when we can't find the image we throw an error in the console too so that developers can be aware.

**Comment by matuzalemsteles** [comment]
I will run the test one more time to see the results.

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:report:2563501819

**Comment by matuzalemsteles** [comment]
I analyzed the tests that failed in the last analysis, some seem flaky and passed locally:

- Execution failed for task ':apps:content-dashboard:content-dashboard-web:packageRunTest'
- Execution failed for task ':apps:analytics:analytics-settings-web:packageRunTest'

Others seem unrelated:

- Execution failed for task ':apps:commerce:commerce-frontend-js:packageRunTest'
- [commerce.commerce-frontend-js.test.components.AccountSelector](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/941073/testReport/commerce.commerce-frontend-js.test.components/AccountSelector)

@ethib137 Does it look good to send forward?

**Comment by ethib137** [comment]
ci:test:stable

**Comment by matuzalemsteles** [comment]
ci:report:2563905166

**Comment by matuzalemsteles** [comment]
ci:test:stable

**Comment by ethib137** [comment]
In general we really need stable to pass to be able to forward. Is stable passing on master currently?

**Comment by matuzalemsteles** [comment]
@ethib137 yes, apparently the last build of master failed https://test-1-27.liferay.com/job/test-portal-testsuite-upstream(master)/2883/.

**Comment by matuzalemsteles** [comment]
But it seems that the [functional-smoke-tomcat90-mysql57-jdk8_stable/0/0](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/865369//consoleText) test is passing on master https://test-1-27.liferay.com/userContent/jobs/test-portal-testsuite-upstream%28master%29/builds/2883/jenkins-report.html

**Comment by matuzalemsteles** [comment]
Okay, I was seeing the test that was failing due to the use of reduced motion and looking at the svg files they do not have animation so there is no need for reduced motion for these use cases so I disabled it for these use cases.

**Comment by matuzalemsteles** [comment]
ci:test:stable

**Comment by ethib137** [comment]
ci:forward:force

**Comment by ilzamcmed** [comment]
ci:forward:force

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:stable

**Comment by matuzalemsteles** [comment]
ci:forward:force

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:forward:force

**Pull request closed without merging**
