### PR TITLE
LPD-15629 - Ensure that the link is not associated with the previous paragraph.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-15629

This test is failing only on CI. In order to reproduce this locally we have to change the display resolution to something smaller like `1080 x 760`. At this smaller resolution, AXE is interpreting the link as being part of the previous paragraph and therefore comparing the contrast between link text and body text. We are not concerned with the contrast between links and body text color because we have a setting in the accessibility menu that forces all links to be underlined so that they are distinguishable without needing to increase text size.

The fix simply adds a div around the link so that it is not accidentally associated with the previous paragraph.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:clay

**Comment by pat270** [comment]
ci:test:clay

**Review by pat270 — APPROVED** [review]

**Comment by pat270** [comment]
Failures look unrelated.

**Comment by pat270** [comment]
ci:forward:force

**Comment by ethib137** [comment]
ci:help

**Comment by ethib137** [comment]
ci:test:accessibility

**Pull request closed without merging**
