### PR TITLE
LPD-7012 - Add functional tests for JS Client Extension

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-7012

Resent from: https://github.com/liferay-platform-experience/liferay-portal/pull/534

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:playwright

**Comment by ethib137** [comment]
ci:test:playwright

**Comment by ethib137** [comment]
ci:report:2557350394

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:playwright

**Comment by ethib137** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
There is an issue on test `Create a new JS client extension with a script element attribute`. It's flaky due to the checkbox event not registering the selected client extension. So, clicking on "add" button doesn't add anything. I added a 2 second delay before checking the checkbox and everything works fine (I ran 10 times in a row). 

I'm trying to find a reasonable solution that doesn't involve timeouts

cc: @ethib137 @ilzamcmed

**Comment by ethib137** [comment]
@thiago-buarqque that sounds like it! Could you see if you're able to have the search container initially render disabled checkboxes and then when the Javascript is loading enable the checkboxes at that point? I think it would be [here](https://github.com/liferay/liferay-portal/blob/01119a221b59b69f534548e418d161e13149e301/modules/apps/item-selector/item-selector-web/src/main/resources/META-INF/resources/js/ViewItemSelectorViewDescriptorMultiple.ts#L24). 

This is what playwright recommends in their docs for handling this situation, so I'd like to try it out. We would still need to double check with @marcoscv-work that this is okay for accessibility, but it could be a good option.

**Comment by thiago-buarqque** [comment]
@ethib137 wouldn't be better to render the checkboxes already with the events? Not sure where they're rendered, but it seems to be the optimal case

**Comment by thiago-buarqque** [comment]
> This is what playwright recommends in their docs for handling this situation

Also, could you provide the docs link for what you mentioned?

**Comment by thiago-buarqque** [comment]
@ethib137 @ilzamcmed So, I found a solution that works fine and don't require much considering the time we have to deliver the story. Please check #543 description for more info.

**Pull request closed without merging**
