### PR TITLE
LPD-44022 Make playwright heading selector more specific to reduce fl…

### PR DESCRIPTION
**Pull request by pat270**
…akiness

https://liferay.atlassian.net/issues/LPD-44022

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:playwright

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:playwright

**Review by thiago-buarqque — APPROVED** [review]
@pat270  I guess this is fine, have you looked other ways of making this selector more specific without the need of many CSS class selectors?  I mean with the usage of `getByRole` and similars

**Comment by pat270** [comment]
@thiago-buarqque technically the original selector should work, but I don't know why playwright is choking on it sometimes.

**Comment by thiago-buarqque** [comment]
@pat270 Ah I see, the usual mysteries of Playwright behavior in our code. It's fine then

**Comment by pat270** [comment]
ci:forward

**Pull request closed without merging**
