### PR TITLE
LPS-200606 Fix accessibility warnings for Control Menu, Product Menu and Footers

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPS-200606

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reevaluate:1377401_15738

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@ethib137 I checked all the logs and the only thing that seems related is `ProductMenuBodyTopDynamicInclude.java` changed div to nav. But this test failure isn't listed in the logs listed under **Failures unique to this pull**.

```
[exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.PortalSmoke#Smoke] STANDARD_ERROR
[exec]     java.lang.Exception: Element is not present at "//div[contains(@id,'sidenavSliderId') and contains(@class,'open') and not(contains(@class,'sidenav-transition')) and not(contains(@class,'closed'))]"
[exec]       at ProductMenuHelper.openProductMenu(/opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/productnavigation/ProductMenuHelper.macro:56)
[exec]       at ProductMenu.gotoPortlet(/opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/productnavigation/ProductMenu.macro:90)
[exec]       at Smoke.runSmoke(/opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Smoke.macro:24)
[exec]       at PortalSmoke.Smoke(/opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/portalsmoke/PortalSmoke.testcase:46)
[exec]       at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.assertTrue(BaseWebDriverImpl.java:4693)
[exec]       at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4731)
[exec]       at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.waitForElementPresent(BaseWebDriverImpl.java:3288)
[exec]       at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
[exec]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[exec]       at java.lang.reflect.Method.invoke(Method.java:498)
[exec]       at com.liferay.poshi.runner.PoshiRunnerExecutor.lambda$invokeLiferaySeleniumMethod$0(PoshiRunnerExecutor.java:1298)
[exec]       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[exec]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[exec]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[exec]       at java.lang.Thread.run(Thread.java:750)
```

**Comment by ethib137** [comment]
Resent with rebase here: https://github.com/liferay-platform-experience/liferay-portal/pull/427

**Pull request closed without merging**
