### PR TITLE
LPD-23825

### PR DESCRIPTION
**Pull request by SelenaAungst**
https://liferay.atlassian.net/browse/LPD-23825

### CODE REVIEW

**Review by ethib137 — APPROVED** [review]
LGTM. Thanks.

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:forward

**Comment by SelenaAungst** [comment]
Thanks @ethib137 @pat270 !

**Pull request closed without merging**
